### ISSUE TITLE
balena preload fails to setup loopback device Mac OS

### ISSUE THREAD

**Issue by BrantRoom3327** [balena-io/balena-cli#1066]
- **Cli version: 0.96**
- **Standalone install: yes**
- **Node version: 8.81**
- **Npm version: 5.51**
- **Operating system and architecture: Mac OS 10.14.2**

I'm trying to get balena to preload an image that is already running in the more standard way of the container being downloaded after the first time the image is flashed to the unit.  Here is the command I ran and output:
```
➜  balena balena preload ./balena.img --app KCF2 -c latest
Building Docker preloader image. [========================] 100%



| Creating preloader container
/ Starting preloader container
\ Fetching application KCF2
| Reading image information
1: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
 ---> 3199d44bca79
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
 ---> e39efb2cb206
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> e8ca198c50d4
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
 ---> 988dc3425a28
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> d72fcde16039
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> 9679696c98ed
Successfully built 9679696c98ed
Successfully tagged balena/balena-preload:latest
Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 825, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 785, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 667, in get_images_and_supervisor_version
    inner_image_path = get_inner_image_path(mountpoint)
  File "/usr/src/app/preload.py", line 625, in get_inner_image_path
    device_type = get_device_type()
  File "/usr/src/app/preload.py", line 605, in get_device_type
    result = get_json("flash-boot", "device-type.json", image=image)
  File "/usr/src/app/preload.py", line 594, in get_json
    with part.mount_context_manager() as mountpoint:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 103, in mount_context_manager
    with losetup_context_manager(image, offset, size) as device:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 87, in losetup_context_manager
    device = losetup(*args).stdout.decode("utf8").strip()
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /sbin/losetup -f --show --offset 4194304 --sizelimit 41943040 /img/balena.img

  STDOUT:


  STDERR:
losetup: /img/balena.img: failed to set up loop device: No such file or directory

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io
```

I'm not sure if i have something misconfigured with docer on my system.  What would be a good next step to ensure the configuration is correct?

Thanks

**Comment by zvin** [comment]
@BrantRoom3327 what `balena-cli` version are you using?
Also what version of `balena-preload` is installed? You can use `npm ls balena-preload` to know.

**Comment by BrantRoom3327** [comment]
@zvin The balena-cli version i am using is the 0.9.9 version as reported by "balena version" and the balena-preload returned from ```npm ls balena-preload``` is 0.8.1    If you have any other questions feel free to ask.  Thanks!

**Comment by zvin** [comment]
@BrantRoom3327 did you mean `balena-cli` `9.9.0` and `balena-preload` `8.1.0` ?

**Comment by BrantRoom3327** [comment]
@zvin Yes, yes I did.  Sorry if that wasn't clear.

**Comment by zvin** [comment]
This looks very similar to https://github.com/balena-io/balena-cli/issues/1008 .
The above was solved by bind mounting the host's `/dev` to the container's `/dev`. But this was for linux hosts.
I'm not sure how docker works on mac.
This needs some investigation.
