### ISSUE TITLE
balena deploy fails for additional members of legacy apps

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1102]
As reported in the forums:
https://forums.balena.io/t/ssh-agent-build-forwarding/5300
```
user@server:~/Github# DEBUG=1 balena deploy legacy/app d9541f4cab41
[Debug]   Parsing input...
[Debug]   Loading project...
[Info]    Creating default composition with image: d9541f4cab41
[Debug]   Creating project...
[Info]    Everything is up to date (use --build to force a rebuild)
[Warn]    Target application requires legacy deploy method.
[Info]    Initializing deploy...
[Info]    Uploading [========================] 100% eta 0s            
[Debug]   Received data: {"type":"error","message":"Unauthorized. Cannot access application"}
[Error]   Deploy failed
Error: Remote error: undefined
    at Request.handleMessage (/snapshot/balena-cli/build/utils/deploy-legacy.js:67:25)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/snapshot/balena-cli/node_modules/request/request.js:1080:12)
    at emitOne (events.js:96:13)
    at IncomingMessage.emit (events.js:188:7)
    at IncomingMessage.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

Known workarounds:
* Use CLI version 6.10.3
* Upgrade to a new (non-legacy) app

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_hc5v)

**Comment by pdcastro** [comment]
On investigation, I've gathered that since a refactoring about a year ago, the CLI was discarding the 'owner' part of 'owner/appName' for legacy applications when creating the builder endpoint URL.
