### ISSUE TITLE
I didn't have enought privileges :/

### ISSUE THREAD

**Issue by Basilou-R** [balena-io/balena-cli#1103]
- **Cli version: v9.12.0**
- **Standalone install: yes**
- **Node version: v10.15.1**
- **Npm version: 6.4.1**
- **Operating system and architecture: Windows 7 64bits**

---

I have re-install 3 times balena CLI but i have the same error everytime :/
I even reassigned permissions, but it doesn't matter.
Thanks you everyoneto be kind enough to reply to my message ! ^^
![image](https://user-images.githubusercontent.com/17341929/52906452-7e565080-324c-11e9-92a4-35daece18323.png)

**Comment by bellduck** [comment]
I have this issue as well, but on macOS 10.14.2.

When I run the command with `sudo` and `DEBUG=1 BLUEBIRD_DEBUG=1` this is what i get:

`Password:
[debug] Using . as build source
| Packaging the project source...Error: EPERM: operation not permitted, scandir '/Users/USER/Library/Cookies'
    at module.exports (/usr/local/lib/node_modules/balena-cli/node_modules/stream-to-array/index.js:16:19)
    at fromReadable (/usr/local/lib/node_modules/balena-cli/node_modules/stream-to-promise/index.js:16:17)
    at streamToPromise (/usr/local/lib/node_modules/balena-cli/node_modules/stream-to-promise/index.js:10:31)
    at getFiles (/usr/local/lib/node_modules/balena-cli/build/utils/compose.js:142:12)
    at Object.tarDirectory (/usr/local/lib/node_modules/balena-cli/build/utils/compose.js:150:10)
    at /usr/local/lib/node_modules/balena-cli/build/utils/remote-build.js:156:43
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/balena-cli/build/utils/remote-build.js:4:58)
From previous event:
    at runCommand (/usr/local/lib/node_modules/balena-cli/build/app.js:265:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/balena-cli/build/app.js:269:40)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/balena-cli/bin/balena:11:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

If you need help, don't hesitate in contacting us at:

  GitHub: https://github.com/balena-io/balena-cli/issues/new
  Forums: https://forums.balena.io`

**Comment by bellduck** [comment]
I got it working! 

I had to `cd` into the extracted folder `balena-dash-master` before running the command.

**Comment by pdcastro** [comment]
As mentioned above, it is necessary to execute a `cd` command to the project folder before running `balena push`, something like:
```
cd balena-pihole

balena push Pi-Hole
```

There is another open issue, #1421, for improvements to be made to the CLI to detect that the current folder "doesn't look right", and print a more user-friendly error message.

As it looks like this is more of a troubleshooting matter than a CLI bug (other than #1421), if something is still not working I suggest reaching out in the [balenaCloud forum](https://forums.balena.io/c/balena-cloud), which is monitored by the balena support team who will be happy to help. Thank you for trying out balena's platform!
