### ISSUE TITLE
Balena build emulated fail Invalid ELF image for this architecture

### ISSUE THREAD

**Issue by buschbapti** [balena-io/balena-cli#1154]
Hello,

I am trying to build a multi-container application on my computer and deploy it on a raspberry pi. The reason I don't push it directly to the pi is that the compilation of some code in my images requires more than 1GB of RAM to be performed. Here is the beginning of one Dockerfile I am trying to build:

```
FROM ros:melodic-ros-base
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y git build-essential sudo && rm -rf /var/lib/apt/lists/*
```

The `ros:melodic-ros-base` is compatible with ARM as if I use `balena push` directly it compiles correctly. However, using the command `DEBUG=1 balena build --deviceType raspberrypi3 --arch armv7hf --logs --source . --emulated` the build fail at the package install line with:
 
```
/bin/sh: Invalid ELF image for this architecture
[Error]   Build failed
Error: The command '/tmp/qemu-execve -execve /bin/sh -c apt-get update && apt-get install -y git build-essential sudo && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 255
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:178:23)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:193:13)
    at Stream.EventEmitter.emit (domain.js:481:20)
    at drain (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/usr/lib/node_modules/balena-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:706:20)
    at IncomingMessage.emit (events.js:193:13)
    at IncomingMessage.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at IncomingMessage.Readable.push (_stream_readable.js:232:10)
    at HTTPParser.parserOnBody (_http_common.js:126:22)
    at Socket.socketOnData (_http_client.js:447:20)
    at Socket.emit (events.js:193:13)
    at Socket.EventEmitter.emit (domain.js:481:20)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:150:17)
```

All the images im my application that have to perform the installation of some packages fail with that line, except those that inherit from a balena base image (e.g. `balenalib/raspberrypi3-ubuntu`). Now the image I am building from (mostly ros images) are compatible with ARM so I believe the problem comes from the cross-compilation using `qemu`. Any idea on what could go wrong? Is there something else to specify in the command line?

Thanks a lot in advance and thanks for that great project.

**Comment by pdcastro** [comment]
@buschbapti, I can think of 2 suggestions:
* Have a look a the following blog post, specifically the section entitled _"These are not the binaries you're looking for"_ that mentions `binfmt_misc`. I am not sure if it solves the "Invalid ELF image" error you are getting, but it's probably worth a try:
https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
* Alternatively, if you are using balenaCloud to deploy to your devices, you could try building on the balenaCloud native ARM builders instead of using emulation. Just a few days ago we added support for native armv6 as well, covering a wider range of native ARM architectures. There is a blog about the ARM servers too, a bit old but still relevant:
https://www.balena.io/blog/docker-builds-on-arm-servers-youre-not-crazy-your-builds-really-are-5x-faster/

As I don't believe this a bug in the balena CLI, I suggest you use the balenaCloud forums to ask our support team and wider community for further advice: https://forums.balena.io/c/balena-cloud
They'll be happy to help!

**Comment by pdcastro** [comment]
I have come across this issue again and I realised something else. The `ros:melodic-ros-base` image is for AMD64 (Intel), and they have a separate image for ARM: `arm32v7/ros:melodic-ros-base`. I have tested the following Dockerfile successfully:

```
FROM arm32v7/ros:melodic-ros-base
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y git build-essential sudo && rm -rf /var/lib/apt/lists/*
```
```
$ balena build . -e --nocache --logs --deviceType raspberrypi3 --arch armv7hf
[Info]    Creating default composition with source: /Users/paulo/Downloads/support/ros
[Info]    Building for armv7hf/raspberrypi3
[Build]   Building services...
[Build]   main Preparing...
[Info]    Emulation is enabled
[Build]   main Step 1/4 : FROM arm32v7/ros:melodic-ros-base
[Build]   main  ---> bc770caa4bba
[Build]   main Step 2/4 : COPY [".balena/qemu-execve","/tmp/qemu-execve"]
[Build]   main  ---> ca531f0bddd2
[Build]   main Step 3/4 : ENV DEBIAN_FRONTEND="noninteractive"
[Build]   main  ---> Running in 7662de65e8c5
[Build]   main Removing intermediate container 7662de65e8c5
[Build]   main  ---> 0345accdfffa
[Build]   main Step 4/4 : RUN ["/tmp/qemu-execve","-execve","/bin/sh","-c","apt-get update && apt-get install -y git build-essential sudo && rm -rf /var/lib/apt/lists/*"]
[Build]   main  ---> Running in a68df586595f
[Build]   main Get:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease [242 kB]
[Build]   main Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]
[Build]   main Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
[Build]   main Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [88.7 kB]
[Build]   main Get:5 http://packages.ros.org/ros/ubuntu bionic InRelease [4669 B]
[Build]   main Get:6 http://ports.ubuntu.com/ubuntu-ports bionic/multiverse armhf Packages [157 kB]
[Build]   main Get:7 http://ports.ubuntu.com/ubuntu-ports bionic/main armhf Packages [1277 kB]
[Build]   main Get:8 http://ports.ubuntu.com/ubuntu-ports bionic/universe armhf Packages [11.0 MB]
[Build]   main Get:9 http://ports.ubuntu.com/ubuntu-ports bionic/restricted armhf Packages [12.5 kB]
[Build]   main Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe armhf Packages [1101 kB]
[Build]   main Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main armhf Packages [728 kB]
[Build]   main Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/restricted armhf Packages [10.6 kB]
[Build]   main Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-updates/multiverse armhf Packages [3995 B]
[Build]   main Get:14 http://ports.ubuntu.com/ubuntu-ports bionic-backports/universe armhf Packages [4247 B]
[Build]   main Get:15 http://ports.ubuntu.com/ubuntu-ports bionic-backports/main armhf Packages [2490 B]
[Build]   main Get:16 http://ports.ubuntu.com/ubuntu-ports bionic-security/restricted armhf Packages [5013 B]
[Build]   main Get:17 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe armhf Packages [633 kB]
[Build]   main Get:18 http://ports.ubuntu.com/ubuntu-ports bionic-security/main armhf Packages [454 kB]
[Build]   main Get:19 http://ports.ubuntu.com/ubuntu-ports bionic-security/multiverse armhf Packages [2077 B]
[Build]   main Get:20 http://packages.ros.org/ros/ubuntu bionic/main armhf Packages [547 kB]
[Build]   main Fetched 16.4 MB in 11s (1518 kB/s)
[Build]   main Reading package lists...
[Build]   main Reading package lists...
[Build]   main Building dependency tree...
[Build]   main Reading state information...
[Build]   main build-essential is already the newest version (12.4ubuntu1).
[Build]   main build-essential set to manually installed.
[Build]   main git is already the newest version (1:2.17.1-1ubuntu0.4).
[Build]   main git set to manually installed.
[Build]   main sudo is already the newest version (1.8.21p2-3ubuntu1.1).
[Build]   main sudo set to manually installed.
[Build]   main 0 upgraded, 0 newly installed, 0 to remove and 88 not upgraded.
[Build]   main Removing intermediate container a68df586595f
[Build]   main  ---> 972e8c71e168
[Build]   main Successfully built 972e8c71e168
[Build]   main Successfully tagged ros_main:latest
[Build]   main Waiting...
[Build]   Built 1 service in 1:05
[Success] Build succeeded!
```

> The `ros:melodic-ros-base` is compatible with ARM as if I use `balena push` directly it compiles correctly.

Well, this may only have meant that an AMD64 image (Intel, not really ARM) was sent to the cloud builders, and they were happy to build it.

I think this resolves the issue, so I'm closing it.

**Comment by buschbapti** [comment]
Sorry for not following up on that. Yes that actually resolve the issue. Thanks for your help.
