### ISSUE TITLE
Balena preload error

### ISSUE THREAD

**Issue by dborgesr** [balena-io/balena-cli#1189]
- **Cli version:10.6.0**
- **Standalone install:yes**
- **Node version:8.0.0**
- **Npm version:6.9.0**
- **Operating system and architecture: Mac Mojave 10.14.1**

So when i run: 
balena preload ./nanotid_rpi0.img --app 1040190 

The output is as follows:

```
1: Step 1/7 : FROM docker:17.10.0-ce-dind
 ---> 9769e0f3f9cb
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs docker util-linux sfdisk file coreutils sgdisk
 ---> Using cache
 ---> eb3a13f34a0e
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
 ---> 671019e48615
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> c9470ee355cd
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
 ---> 3f9b452d9fd2
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> f36802d802f5
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> 29c02a4806a8
Successfully built 29c02a4806a8
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 108:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpsn243fp4/docker --host=tcp://0.0.0.0:50054

  STDOUT:


  STDERR:
time="2019-04-24T16:33:19.109887000Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2019-04-24T16:33:19.112537100Z" level=info msg="libcontainerd: new containerd process, pid: 122"
Error starting daemon: error initializing graphdriver: driver not supported


Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 825, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 785, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 669, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 644, in _get_images_and_supervisor_version
    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 511, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 480, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpsn243fp4/docker --host=tcp://0.0.0.0:50054

  STDOUT:


  STDERR:
time="2019-04-24T16:33:19.109887000Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2019-04-24T16:33:19.112537100Z" level=info msg="libcontainerd: new containerd process, pid: 122"
Error starting daemon: error initializing graphdriver: driver not supported

Additional information may be available in debug mode. Prefix the command
line with DEBUG=1, i.e.:  DEBUG=1 balena ...
If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

```

I tried wiping my Docker image, but no go. I'm kind of at a loss at this point, I'm not able to install balena-cli through npm as well, that's why i went down the path of downloading the binaries, not sure if that's related.

--Thank you

**Comment by pdcastro** [comment]
I believe this issue is a duplicate of #1099.

@dborgesr, I understand that this issue is caused by the removal of support for the AUFS driver (`--storage-driver=aufs`) in [Docker Community Edition 2.0.0.0-mac78 2018-11-19](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-2000-mac78-2018-11-19) (which ships with Docker 18.09.0+) and later versions.

Unfortunately the only known known workaround at the moment is to downgrade to [Docker Community Edition 18.06.1-ce-mac73 2018-08-29](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18061-ce-mac73-2018-08-29) (which ships with Docker 18.06.1-ce).

**Comment by dborgesr** [comment]
Ah my apologies! I didn't see the issue while scanning. 

Welp, that's unfortunate, guess i'll do a downgrade and hope nothing else breaks -_-, i'll close this issue then.
