### ISSUE TITLE
"Creation of this event was denied due to rate limiting" (Sentry errors mask real errors)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1193]
We use Sentry.io to get CLI error reports. But they apply rate limiting and monthly caps, and when this happens, the error reported on the console to the user is the Sentry error instead of the real cause, making the situation worse and preventing debugging.
Any Sentry-related errors should be either omitted, or made less prominent in favour of the original error.

**Comment by zvin** [comment]
error message (this happened while using `balena os download`:
```
Error: HTTP Error (429): Creation of this event was denied due to rate limiting
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/balena-cli/node_modules/raven/lib/transports.js:56:15)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:210:5)
    at ClientRequest.EventEmitter.emit (domain.js:476:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at TLSSocket.Readable.push (_stream_readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  response: IncomingMessage {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: true,
      decoder: [StringDecoder],
      encoding: 'utf8'
    },
    readable: true,
    _events: [Object: null prototype] { end: [Function: responseOnEnd] },
    _eventsCount: 1,
    _maxListeners: undefined,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'sentry.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'sentry.io',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      timeout: 1000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 551754,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 1000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 116285,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 551765,
        [Symbol(triggerId)]: 551763
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'sentry.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'sentry.io',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      timeout: 1000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 551754,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 1000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 116285,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 551765,
        [Symbol(triggerId)]: 551763
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: false,
    headers: {
      server: 'nginx',
      date: 'Wed, 23 Oct 2019 13:06:18 GMT',
      'content-type': 'application/json',
      'content-length': '92',
      connection: 'keep-alive',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS',
      'x-content-type-options': 'nosniff',
      'content-language': 'en',
      'access-control-expose-headers': 'X-Sentry-Error, Retry-After',
      'x-sentry-error': 'Creation of this event was denied due to rate limiting',
      vary: 'Accept-Language, Cookie',
      expires: 'Wed, 23 Oct 2019 13:06:18 GMT',
      'retry-after': '93',
      'last-modified': 'Wed, 23 Oct 2019 13:06:18 GMT',
      'x-xss-protection': '1; mode=block',
      allow: 'GET, POST, HEAD, OPTIONS',
      'cache-control': 'no-cache, no-store, must-revalidate, max-age=0',
      'access-control-allow-origin': '*',
      'access-control-allow-headers': 'X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization',
      'x-frame-options': 'deny',
      'x-served-by': 'api-store-206a9130',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload'
    },
    rawHeaders: [
      'Server',
      'nginx',
      'Date',
      'Wed, 23 Oct 2019 13:06:18 GMT',
      'Content-Type',
      'application/json',
      'Content-Length',
      '92',
      'Connection',
      'keep-alive',
      'Access-Control-Allow-Methods',
      'GET, POST, HEAD, OPTIONS',
      'X-Content-Type-Options',
      'nosniff',
      'Content-Language',
      'en',
      'Access-Control-Expose-Headers',
      'X-Sentry-Error, Retry-After',
      'X-Sentry-Error',
      'Creation of this event was denied due to rate limiting',
      'Vary',
      'Accept-Language, Cookie',
      'Expires',
      'Wed, 23 Oct 2019 13:06:18 GMT',
      'Retry-After',
      '93',
      'Last-Modified',
      'Wed, 23 Oct 2019 13:06:18 GMT',
      'X-XSS-Protection',
      '1; mode=block',
      'Allow',
      'GET, POST, HEAD, OPTIONS',
      'Cache-Control',
      'no-cache, no-store, must-revalidate, max-age=0',
      'Access-Control-Allow-Origin',
      '*',
      'Access-Control-Allow-Headers',
      'X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization',
      'X-Frame-Options',
      'deny',
      'X-Served-By',
      'api-store-206a9130',
      'Strict-Transport-Security',
      'max-age=31536000; includeSubDomains; preload'
    ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '',
    method: null,
    statusCode: 429,
    statusMessage: 'TOO MANY REQUESTS',
    client: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'sentry.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'sentry.io',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: true,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: [HTTPParser],
      _httpMessage: [ClientRequest],
      timeout: 1000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 551754,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 1000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 116285,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(asyncId)]: 551765,
        [Symbol(triggerId)]: 551763
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _consuming: false,
    _dumped: false,
    req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 3752,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /api/149239/store/ HTTP/1.1\r\n' +
        'XXXXXXXXXXXXXXXXXXXXXXXXX' +
        'Content-Type: application/octet-stream\r\n' +
        'Content-Length: 3752\r\n' +
        'Host: sentry.io\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      path: '/api/149239/store/',
      _ended: false,
      res: [Circular],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      timeoutTimer: null,
      [Symbol(kNeedDrain)]: false,
      [Symbol(isCorked)]: false,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    }
  },
  statusCode: 429,
  reason: 'Creation of this event was denied due to rate limiting',
  sendMessage: 'XXXXXXX',
  requestHeaders: {
    'X-Sentry-Auth': XXXXXXX,
    'Content-Type': 'application/octet-stream',
    'Content-Length': 3752
  },
  eventId: 'bf5ac4188bf24cd79cfc74d571b21f5e'
}
```

**Comment by srlowe** [comment]
There's a raven issue about this (feature): https://github.com/getsentry/sentry-javascript/issues/1557

Since raven is the legacy client it's probably best to upgrade to new sentry client (#1523 ), and then see where we are with this issue.

**Comment by pdcastro** [comment]
CLI release 11.28.14 upgraded the Sentry client and suppressed Sentry reporting of a few selected "expected" errors. It may or may not have resolved this issue: it's difficult to test / reproduce it. I am going to close this issue as a way of inviting comments / reports that it has not actually been fixed (and that I should not have closed the issue) :-)  (Otherwise, people see that this issue is open and assume there is no need to report errors anymore.)
