### ISSUE TITLE
Install seems to fail on node 12

### ISSUE THREAD

**Issue by imrehg** [balena-io/balena-cli#1207]
- **Cli version:** v10.9.1
- **Standalone install:** no
- **Node version:** v12.1.0
- **Npm version:** 6.9.0
- **Operating system and architecture:** Archlnux 64-bit

Logs:

```
make: *** [lzma_native.target.mk:120: Release/obj.target/lzma_native/src/filter-array.o] Error 1
make: Leaving directory '/home/greg/resin/resin-cli/node_modules/lzma-native/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/greg/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 5.0.10-arch1-1-ARCH
gyp ERR! command "/home/greg/.nvm/versions/node/v12.1.0/bin/node" "/home/greg/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64/lzma_native.node" "--module_name=lzma_native" "--module_path=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/greg/resin/resin-cli/node_modules/lzma-native
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/greg/.nvm/versions/node/v12.1.0/bin/node /home/greg/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/greg/resin/resin-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1000:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:5)
node-pre-gyp ERR! System Linux 5.0.10-arch1-1-ARCH
node-pre-gyp ERR! command "/home/greg/.nvm/versions/node/v12.1.0/bin/node" "/home/greg/resin/resin-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/greg/resin/resin-cli/node_modules/lzma-native
node-pre-gyp ERR! node -v v12.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/greg/.nvm/versions/node/v12.1.0/bin/node /home/greg/.nvm/versions/node/v12.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64/lzma_native.node --module_name=lzma_native --module_path=/home/greg/resin/resin-cli/node_modules/lzma-native/binding-v4.0.3-node-v72-linux-x64 --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: removedrive@1.1.2 (node_modules/removedrive):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for removedrive@1.1.2: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: winusb-driver-generator@1.2.4 (node_modules/winusb-driver-generator):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for winusb-driver-generator@1.2.4: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: macmount@1.0.0 (node_modules/macmount):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for macmount@1.0.0: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lzma-native@4.0.3 install: `node-pre-gyp install --fallback-to-build && rimraf build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lzma-native@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/greg/.npm/_logs/2019-05-01T17_19_01_030Z-debug.log
exit 1
```

Full log: [2019-05-01T17_19_01_030Z-debug.log](https://github.com/balena-io/balena-cli/files/3135304/2019-05-01T17_19_01_030Z-debug.log)

Using node v10.15.3 (npm v6.4.1) installs successfully.

---

*Please keep in mind that we try to use the issue tracker of this repository for specific bug reports & CLI feature requests. General & troubleshooting questions are encouraged to be posted to the [balena forums](https://forums.balena.io) where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another issue describing the same problem or feature please add your information to the existing issue's comments.*

**Comment by CameronDiver** [comment]
This is now working, I'm not sure on the specific change, but going to close this issue.
