### ISSUE TITLE
balena apps: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1241]
https://forums.balena.io/t/facing-issue-in-openbalena-configuration/7927/67
```
$ balena version
10.13.3
$ balena apps
TypeError: Cannot read property 'length' of undefined
    at /snapshot/balena-cli/build/actions/app.js:75:60
    at Array.forEach (native)
    at /snapshot/balena-cli/build/actions/app.js:74:20
    at tryCatcher (/snapshot/balena-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise.module.exports.Promise._fulfill (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.module.exports.PromiseArray._resolve (/snapshot/balena-cli/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray.module.exports.MappingPromiseArray._promiseFulfilled (/snapshot/balena-cli/node_modules/bluebird/js/release/map.js:101:18)
    at MappingPromiseArray.module.exports.PromiseArray._iterate (/snapshot/balena-cli/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/snapshot/balena-cli/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise.module.exports.Promise._settlePromise (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/balena-cli/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/snapshot/balena-cli/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/snapshot/balena-cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/snapshot/balena-cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.e.Async.drainQueues (/snapshot/balena-cli/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
- **Cli version:** 10.13.3
- **Standalone install:** 
- **Node version:**
- **Npm version:**
- **Operating system and architecture:**

**Comment by thgreasi** [comment]
See: https://github.com/balena-io/balena-cli/blob/3b5f3c6665e4d8505058d7a5f5be92c11dc750b1/lib/actions/app.coffee#L88-L98
