### ISSUE TITLE
VirtualBox no SSH access

### ISSUE THREAD

**Issue by caevv** [balena-io/balena-cli#1252]
I followed this tutorial:
https://www.balena.io/blog/no-hardware-use-virtualbox/

But I don't have SSH access from UI, says needs version +v2.0.

From cli I get:

```
TypeError: Invalid Version: null
    at new SemVer (/usr/local/lib/node_modules/balena-cli/node_modules/semver/semver.js:305:11)
    at compare (/usr/local/lib/node_modules/balena-cli/node_modules/semver/semver.js:614:10)
    at Function.lt (/usr/local/lib/node_modules/balena-cli/node_modules/semver/semver.js:648:10)
    at /usr/local/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:169:16
    at tryCatcher (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/method.js:15:34
    at /usr/local/lib/node_modules/balena-cli/node_modules/balena-sdk/build/models/device.js:587:14
    at tryCatcher (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:637:19)
    at process.topLevelDomainCallback (domain.js:126:23)```

**Comment by pdcastro** [comment]
@caevv, thanks for reporting this issue. Regarding _"says needs version +v2.0",_ I guess this refers to the version of the balenaOS image that was downloaded through the web dashboard. Looking at the tutorial, at the following step:

> From the dashboard, download the device OS,

Could you check what version of balenaOS (Intel NUC) you had downloaded? Try downloading the latest available version, which at the time of this writing was `2.36.0+rev2`.

**Comment by caevv** [comment]
Yes, it's referring to the balenaOS image, the one I'm using is this:
`balena-cloud-test-intel-nuc-2.32.0+rev4-dev-v9.14.0`

I tried `2.36.0+rev2` now, and same issue.

**Comment by pdcastro** [comment]
@caevv, I was successful in opening ssh terminals to a balenaOS NUC image running on VirtualBox, both via the web dashboard and with the CLI. Some details about my setup:

* Host OS: macOS 10.14.4
* VirtualBox version 6.0.8
* balenaOS v2.36.0+rev2 (development image)
* balena CLI v10.13.5

Terminal on my laptop:
```
$ balena version
10.13.5
$ balena ssh 27d8e0c6377e8f562725f9af75a40aed -s
Connecting to: 27d8e0c6377e8f562725f9af75a40aed
=============================================================
    Welcome to balenaOS
=============================================================
root@27d8e0c:~# cat /etc/issue
balenaOS 2.36.0 \n \l
```

Dashboard screenshot:
![Screenshot 2019-05-24 at 02 07 49](https://user-images.githubusercontent.com/15091591/58295806-df9c3b80-7dc8-11e9-94fb-6945d766f5ae.png)

I believe I have closely followed every step in the tutorial post you linked.

It sounds like you got error messages pointing to the balenaOS version both from the web dashboard _("says needs version +v2.0")_ and the CLI ("Invalid Version: null"). I agree that the CLI should not crash with that stack trace (and as far as it crashes, it is a bug - thanks for reporting it), but I suspect that the issue you're facing is ultimately to do with the balenaOS installation (perhaps VirtualBox configuration) rather than the CLI. For this reason, if you're still facing the issue, I would recommend asking for troubleshooting help in the forums: https://forums.balena.io/c/balena-cloud
The forum community and balena's support team are very responsive and will be happy to help further!

**Comment by caevv** [comment]
Thanks for looking into it, glad it worked for you, may be something that I'm doing. I'll close and reply here again when I look into it again.
