### ISSUE TITLE
Error building balena-cli as part of openbalena install process - usb@1.3.10

### ISSUE THREAD

**Issue by dtischler** [balena-io/balena-cli#1370]
- **Operating system version:** Ubuntu 18.04 VPS
- **32/64 bit OS and processor:** x86-64
- **Install method:** npm installer
- **If npm install, Node.js and npm version:** Node v8.10.0 and npm v3.5.2 (default installation brought in these versions).

---

On a freshly provisioned Digital Ocean Droplet, following the installation guide for openbalena located here:  https://www.balena.io/open/docs/getting-started , results in the below error when attempting the "Installing the CLI Client" step.  Unsure if this repo is the correct location to report the error, or, if the openbalena repo is the proper location, sorry if this is misplaced, thanks.

```
root@ubuntu-openbalena-cli:~# uname -a
Linux ubuntu-openbalena-cli 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu-openbalena-cli:~# npm install balena-cli -g --production --unsafe-perm
/usr/local/bin/balena -> /usr/local/lib/node_modules/balena-cli/bin/balena

> fsevents@1.2.9 install /usr/local/lib/node_modules/balena-cli/node_modules/fsevents
> node install


> ref-napi@1.4.0 install /usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ref-napi
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ref-napi/build'
  SOLINK_MODULE(target) Release/obj.target/node_modules/node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ref-napi/build'

> ffi-napi@2.4.3 install /usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'
  SOLINK_MODULE(target) Release/obj.target/../node-addon-api/src/nothing.node
  COPY Release/nothing.node
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/closures.c:433:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
       ftruncate (execfd, offset);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
    FFI_ASSERT (0);
                  ^
../deps/libffi/src/x86/ffi64.c:156:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
       {
       ^
../deps/libffi/src/x86/ffi64.c:183:5: note: here
     case FFI_TYPE_FLOAT:
     ^~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
In file included from /usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi.h:1542:0,
                 from ../src/ffi.h:22,
                 from ../src/ffi.cc:1:
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:108:8: warning: mangled name for ‘static void Napi::details::FinalizeData<T, Finalizer, Hint>::Wrapper(napi_env, void*, void*) [with T = char; Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = char*() throw ()]::<lambda(Napi::Env, char*)>; Hint = void]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
   void Wrapper(napi_env env, void* data, void* finalizeHint) {
        ^~~~~~~
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:108:8: warning: mangled name for ‘static void Napi::details::FinalizeData<T, Finalizer, Hint>::Wrapper(napi_env, void*, void*) [with T = char; Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(void*, const char*) throw ()]::<lambda(Napi::Env, char*)>; Hint = void]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:108:8: warning: mangled name for ‘static void Napi::details::FinalizeData<T, Finalizer, Hint>::Wrapper(napi_env, void*, void*) [with T = char; Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = int(void*) throw ()]::<lambda(Napi::Env, char*)>; Hint = void]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:108:8: warning: mangled name for ‘static void Napi::details::FinalizeData<T, Finalizer, Hint>::Wrapper(napi_env, void*, void*) [with T = char; Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(const char*, int) throw ()]::<lambda(Napi::Env, char*)>; Hint = void]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:1662:18: warning: mangled name for ‘static Napi::Buffer<T> Napi::Buffer<T>::New(napi_env, T*, size_t, Finalizer) [with Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = char*() throw ()]::<lambda(Napi::Env, char*)>; T = char]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline Buffer<T> Buffer<T>::New(napi_env env,
                  ^~~~~~~~~
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:1662:18: warning: mangled name for ‘static Napi::Buffer<T> Napi::Buffer<T>::New(napi_env, T*, size_t, Finalizer) [with Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(void*, const char*) throw ()]::<lambda(Napi::Env, char*)>; T = char]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:1662:18: warning: mangled name for ‘static Napi::Buffer<T> Napi::Buffer<T>::New(napi_env, T*, size_t, Finalizer) [with Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = int(void*) throw ()]::<lambda(Napi::Env, char*)>; T = char]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/node-addon-api/napi-inl.h:1662:18: warning: mangled name for ‘static Napi::Buffer<T> Napi::Buffer<T>::New(napi_env, T*, size_t, Finalizer) [with Finalizer = FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(const char*, int) throw ()]::<lambda(Napi::Env, char*)>; T = char]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
In file included from ../src/ffi.cc:1:0:
../src/ffi.h:34:14: warning: mangled name for ‘Napi::Value FFI::WrapPointer(Napi::Env, T*, size_t) [with T = char*() throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline Value WrapPointer(Env env, T* ptr, size_t length = 0) {
              ^~~~~~~~~~~
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t) [with T = char*() throw ()]::<lambda(Napi::Env, char*)>::operator void (*)(Napi::Env, char*)() const’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
                            [](Env,char*){});
                                        ^
../src/ffi.h:40:40: warning: mangled name for ‘static void FFI::WrapPointer(Napi::Env, T*, size_t) [with T = char*() throw ()]::<lambda(Napi::Env, char*)>::_FUN(Napi::Env, char*)’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t)::<lambda(Napi::Env, char*)> [with T = char*() throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:34:14: warning: mangled name for ‘Napi::Value FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(void*, const char*) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline Value WrapPointer(Env env, T* ptr, size_t length = 0) {
              ^~~~~~~~~~~
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(void*, const char*) throw ()]::<lambda(Napi::Env, char*)>::operator void (*)(Napi::Env, char*)() const’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
                            [](Env,char*){});
                                        ^
../src/ffi.h:40:40: warning: mangled name for ‘static void FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(void*, const char*) throw ()]::<lambda(Napi::Env, char*)>::_FUN(Napi::Env, char*)’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t)::<lambda(Napi::Env, char*)> [with T = void*(void*, const char*) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:34:14: warning: mangled name for ‘Napi::Value FFI::WrapPointer(Napi::Env, T*, size_t) [with T = int(void*) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline Value WrapPointer(Env env, T* ptr, size_t length = 0) {
              ^~~~~~~~~~~
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t) [with T = int(void*) throw ()]::<lambda(Napi::Env, char*)>::operator void (*)(Napi::Env, char*)() const’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
                            [](Env,char*){});
                                        ^
../src/ffi.h:40:40: warning: mangled name for ‘static void FFI::WrapPointer(Napi::Env, T*, size_t) [with T = int(void*) throw ()]::<lambda(Napi::Env, char*)>::_FUN(Napi::Env, char*)’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t)::<lambda(Napi::Env, char*)> [with T = int(void*) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:34:14: warning: mangled name for ‘Napi::Value FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(const char*, int) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
 inline Value WrapPointer(Env env, T* ptr, size_t length = 0) {
              ^~~~~~~~~~~
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(const char*, int) throw ()]::<lambda(Napi::Env, char*)>::operator void (*)(Napi::Env, char*)() const’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
                            [](Env,char*){});
                                        ^
../src/ffi.h:40:40: warning: mangled name for ‘static void FFI::WrapPointer(Napi::Env, T*, size_t) [with T = void*(const char*, int) throw ()]::<lambda(Napi::Env, char*)>::_FUN(Napi::Env, char*)’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
../src/ffi.h:40:40: warning: mangled name for ‘FFI::WrapPointer(Napi::Env, T*, size_t)::<lambda(Napi::Env, char*)> [with T = void*(const char*, int) throw ()]’ will change in C++17 because the exception specification is part of a function type [-Wnoexcept-type]
  CXX(target) Release/obj.target/ffi_bindings/src/callback_info.o
  CXX(target) Release/obj.target/ffi_bindings/src/threaded_callback_invokation.o
  SOLINK_MODULE(target) Release/obj.target/ffi_bindings.node
  COPY Release/ffi_bindings.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/net-keepalive/node_modules/ffi-napi/build'

> husky@1.3.1 install /usr/local/lib/node_modules/balena-cli/node_modules/husky
> node husky install

husky > setting up git hooks
Can't find .git, skipping Git hooks installation.
Please check that you're in a cloned repository or run 'git init' to create an empty Git repository and reinstall husky.

> winusb-driver-generator@1.2.4 install /usr/local/lib/node_modules/balena-cli/node_modules/winusb-driver-generator
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/winusb-driver-generator/build'
  SOLINK_MODULE(target) Release/obj.target/Generator.node
  COPY Release/Generator.node
  SOLINK_MODULE(target) Release/obj.target/embedder.node
  COPY Release/embedder.node
  SOLINK_MODULE(target) Release/obj.target/installer_x64.node
  COPY Release/installer_x64.node
  SOLINK_MODULE(target) Release/obj.target/installer_x86.node
  COPY Release/installer_x86.node
  SOLINK_MODULE(target) Release/obj.target/wdi.node
  COPY Release/wdi.node
  TOUCH Release/obj.target/libwdi_configuration.stamp
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/winusb-driver-generator/build'

> drivelist@8.0.6 install /usr/local/lib/node_modules/balena-cli/node_modules/resin-cli-visuals/node_modules/drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/resin-cli-visuals/node_modules/drivelist/build'
  CXX(target) Release/obj.target/drivelist/src/drivelist.o
  CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
  CXX(target) Release/obj.target/drivelist/src/linux/list.o
  SOLINK_MODULE(target) Release/obj.target/drivelist.node
  COPY Release/drivelist.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/resin-cli-visuals/node_modules/drivelist/build'

> ext2fs@1.0.29 install /usr/local/lib/node_modules/balena-cli/node_modules/ext2fs
> prebuild-install || node-gyp rebuild


> drivelist@8.0.6 install /usr/local/lib/node_modules/balena-cli/node_modules/etcher-sdk/node_modules/drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/etcher-sdk/node_modules/drivelist/build'
  CXX(target) Release/obj.target/drivelist/src/drivelist.o
  CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
  CXX(target) Release/obj.target/drivelist/src/linux/list.o
  SOLINK_MODULE(target) Release/obj.target/drivelist.node
  COPY Release/drivelist.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/etcher-sdk/node_modules/drivelist/build'

> drivelist@8.0.6 install /usr/local/lib/node_modules/balena-cli/node_modules/etcher-image-write/node_modules/drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/etcher-image-write/node_modules/drivelist/build'
  CXX(target) Release/obj.target/drivelist/src/drivelist.o
  CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
  CXX(target) Release/obj.target/drivelist/src/linux/list.o
  SOLINK_MODULE(target) Release/obj.target/drivelist.node
  COPY Release/drivelist.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/etcher-image-write/node_modules/drivelist/build'

> mountutils@1.3.19 install /usr/local/lib/node_modules/balena-cli/node_modules/mountutils
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/mountutils/build'
  CXX(target) Release/obj.target/MountUtils/src/mountutils.o
  CXX(target) Release/obj.target/MountUtils/src/worker-unmount.o
  CXX(target) Release/obj.target/MountUtils/src/worker-eject.o
  CXX(target) Release/obj.target/MountUtils/src/linux/functions.o
../src/linux/functions.cpp: In function ‘MOUNTUTILS_RESULT unmount_disk(const char*)’:
../src/linux/functions.cpp:98:21: warning: unused variable ‘result_code’ [-Wunused-variable]
   MOUNTUTILS_RESULT result_code = MOUNTUTILS_SUCCESS;
                     ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/MountUtils.node
  COPY Release/MountUtils.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/mountutils/build'

> drivelist@6.4.6 install /usr/local/lib/node_modules/balena-cli/node_modules/drivelist
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 platform=linux)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/drivelist/build'
  CXX(target) Release/obj.target/drivelist/src/drivelist.o
  CXX(target) Release/obj.target/drivelist/src/device-descriptor.o
  CXX(target) Release/obj.target/drivelist/src/linux/list.o
  SOLINK_MODULE(target) Release/obj.target/drivelist.node
  COPY Release/drivelist.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/drivelist/build'

> xxhash@0.2.4 install /usr/local/lib/node_modules/balena-cli/node_modules/xxhash
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/xxhash/build'
  CXX(target) Release/obj.target/hash/src/hash.o
  SOLINK_MODULE(target) Release/obj.target/hash.node
  COPY Release/hash.node
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/xxhash/build'

> usb@1.3.10 install /usr/local/lib/node_modules/balena-cli/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/thundron/node-usb/releases/download/1.3.10/usb_bindings-v1.3.10-node-v57-linux-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.3.10 and node@8.10.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/usr/local/lib/node_modules/balena-cli/node_modules/usb/build'
make: *** No rule to make target 'Release/obj.target/libusb/libusb/libusb/core.o', needed by 'Release/obj.target/usb.a'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/balena-cli/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-52-generic
gyp ERR! command "/usr/bin/node" "/usr/share/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd /usr/local/lib/node_modules/balena-cli/node_modules/usb
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/share/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/balena-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-52-generic
node-pre-gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/balena-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/balena-cli/node_modules/usb
node-pre-gyp ERR! node -v v8.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/share/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/usr/local/lib/node_modules/balena-cli/node_modules/usb/src/binding --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
/usr/local/lib
└── (empty)

npm WARN resin-register-device@5.0.0 requires a peer of resin-request@^9.0.2 but none was installed.
npm WARN ts-node@8.3.0 requires a peer of typescript@>=2.0 but none was installed.
npm ERR! Linux 4.15.0-52-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "balena-cli" "-g" "--production" "--unsafe-perm"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! usb@1.3.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.3.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the usb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs usb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls usb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
root@ubuntu-openbalena-cli:~#
```

**Comment by thgreasi** [comment]
Hi and thanks for the detailed report.
Is the node version that you are using installed to the system though nvm or is it from a repo/distro specific package?

As noted in the [CLI Installation Instructions](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md#npm-installation) other users have reported that the installation fails on their machine when using non-nvm node v8, but works fine with nvm.
If that's the case for you as well, can you please try installing node through nvm and let us know whether that fixes the issue?

**Comment by pdcastro** [comment]
Looking at the issue from a different angle, the openBalena getting started guide currently says:

> Install the client with:
> `$ npm install balena-cli -g --production --unsafe-perm`

So that's what you did, and it didn't work. But if the guide had instead said:

> Install the CLI with the following instructions:
> https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

Then you might have chosen the standalone zip package for Linux, which I recommend, and you wouldn't have had the problem. In this sense, this issue is related to #1371.

**Comment by pdcastro** [comment]
@dtischler, thanks for reporting this issue. We have updated the openBalena [Getting Started](https://www.balena.io/open/docs/getting-started/) guide for the CLI installation instructions, to point to [INSTALL.md](https://github.com/balena-io/balena-cli/blob/master/INSTALL.md) instead of recommending the npm installation. On Ubuntu, I recommend you try the standalone zip package which is pre-compiled and thus avoids any compilation issues. Alternatively, if you have a reason to prefer npm, I recommend installing node + npm via [nvm](https://github.com/creationix/nvm) instead of using the system packages.

I am closing this issue with the understanding that the suggestions above will solve the problem, but feel free to reopen it if necessary.
