### ISSUE TITLE
env variables with dots in the name cause an error: BadRequestDeviceAPIError: Invalid apps

### ISSUE THREAD

**Issue by krasi-georgiev** [balena-io/balena-cli#1446]
11.11.2
linux with zip installation

The problem is caused by the dots in the env var name, but the loraserver application is designed this way and also running this with official docker-compose works as expected.

```
version: "2.1"

services:
  gatewaybridge:
    image: arribada/lora-gateway-bridge
    ports:
      - 1700:1700/udp
    environment:
      - INTEGRATION.MQTT.AUTH.GENERIC.SERVER=tcp://mosquitto:1883
  mosquitto:
    image: eclipse-mosquitto
```

```
DEBUG=1 balena push 192.168.0.113
```

returns an error:

```
[Debug]   Sending request to http://192.168.0.113:48484/v2/local/target-state
BadRequestDeviceAPIError: Invalid apps
    at promisifiedRequest.Bluebird.fromCallback.then (/snapshot/versioned-source/build/utils/device/api.js:135:27)
    at tryCatcher (/snapshot/versioned-source/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/versioned-source/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise.module.exports.Promise._settlePromise (/snapshot/versioned-source/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/versioned-source/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/versioned-source/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise.module.exports.Promise._fulfill (/snapshot/versioned-source/node_modules/bluebird/js/release/promise.js:643:18)
    at Request.module.exports [as _callback] (/snapshot/versioned-source/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.init.self.callback (/snapshot/versioned-source/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at Request.<anonymous> (/snapshot/versioned-source/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at Request.EventEmitter.emit (domain.js:441:20)
    at IncomingMessage.<anonymous> (/snapshot/versioned-source/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

the same works running it locally with 
```
docker-compose up
```

**Comment by krasi-georgiev** [comment]
@pdcastro I would really appreciate if someone could look into this one as it is another blocker for a project that is about to go in production soon.

**Comment by pdcastro** [comment]
@krasi-georgiev, thank you for reporting and following up on this issue. Apparently the issue is with strict validation by the balena supervisor, so I've cloned this issue to the supervisor repo and added some details (including the relevant code / regular expression):
https://github.com/balena-io/balena-supervisor/issues/1104

A consequence is that a fix/improvement would also require updating balenaOS (or separately upgrading the supervisor only). After the supervisor issue / pull request is merged, it still takes a bit of time until a new balenaOS release incorporates a new supervisor version -- for example, check the following balenaOS Changelog for "Update balena-supervisor":
https://github.com/balena-os/meta-balena/blob/master/CHANGELOG.md

I mention this because of your comment that the issue is a "blocker for a project that is about to go in production". **Consider whether a workaround could be used.** For example, you could perhaps:

* In the docker-compose file, initially use underscore characters instead of dots (INTEGRATION_MQTT_AUTH_GENERIC_SERVER). Then,
* Modify the container's (gatewaybridge) start script / entrypoint to look for and "clone" the relevant environment variables (very early on in the script code). For example, in the case of a shell script:
```
export INTEGRATION.MQTT.AUTH.GENERIC.SERVER="$INTEGRATION_MQTT_AUTH_GENERIC_SERVER"
```
* Note that whenever changes are made to environment variables, the supervisor will restart the affected containers so that the changes are picked up. This means that it should be sufficient to have the variable cloning early on in the start / entrypoint script.

This temporary workaround might be sufficient to please to both the balena supervisor and the loraserver application.

**Comment by krasi-georgiev** [comment]
Thanks for the update, yes I will work on a workaround, I didn't want to change the upstream images, but until this is fixed on the balena side I  will use the workaround.

**Comment by krasi-georgiev** [comment]
closing in favor of balena-io/balena-supervisor#1104
