### ISSUE TITLE
Problem deploying balena dash - error - Invalid ELF image for this architecture

### ISSUE THREAD

**Issue by lakshaygroverr** [balena-io/balena-cli#1614]
CLI - Version 11.24.0
NodeJS Version - 13.8.0
OS - Ubuntu 18.04

[Build]   scheduler     ---> Running in 402810be0460
[Build]   scheduler    /bin/sh: Invalid ELF image for this architecture
[Build]   Built 3 services in 0:01
[Error]   Deploy failed
The command '/tmp/qemu-execve -execve /bin/sh -c chmod +x /wpe-init' returned a non-zero code: 255
Error: The command '/tmp/qemu-execve -execve /bin/sh -c chmod +x /wpe-init' returned a non-zero code: 255
    at Stream.<anonymous> (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:181:23)
    at Stream.stream.write (/snapshot/versioned-source/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:198:13)
    at Stream.EventEmitter.emit (domain.js:448:20)
    at drain (/snapshot/versioned-source/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/snapshot/versioned-source/node_modules/through/index.js:45:5)
    at Parser.exports.parse.parser.onToken (/snapshot/versioned-source/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/snapshot/versioned-source/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/snapshot/versioned-source/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/snapshot/versioned-source/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:708:20)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at IncomingMessage.Readable.push (_stream_readable.js:223:10)
    at HTTPParser.parserOnBody (_http_common.js:122:22)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:287:12)
    at readableAddChunk (_stream_readable.js:268:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at createBuildStream.Bluebird.try.then (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:73:20)
    at Builder.createBuildStream (/snapshot/versioned-source/node_modules/resin-docker-build/build/builder.js:72:97)
    at Promise (/snapshot/versioned-source/node_modules/resin-multibuild/build/build.js:82:17)
    at Object.runBuildTask (/snapshot/versioned-source/node_modules/resin-multibuild/build/build.js:59:12)
    at /snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:157:34
    at Generator.next (<anonymous>)
    at __awaiter (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:4:12)
    at performSingleBuild (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:155:12)
    at Bluebird.map (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:140:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
    at Object.<anonymous> (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:139:39)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/versioned-source/node_modules/resin-multibuild/build/index.js:5:58)
From previous event:
    at runCommand (/snapshot/versioned-source/build/app-capitano.js:181:14)
    at Object.exports.run (/snapshot/versioned-source/build/app-capitano.js:193:39)
    at routeCliFramework (/snapshot/versioned-source/build/preparser.js:39:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1322:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)

**Comment by lakshaygroverr** [comment]
Tried solution already closed but did not work for me! 
updated NodeJs version but no success

**Comment by lakshaygroverr** [comment]
This thing worked when i deployed code through balena cloud servers using - balena push myApp but facing issues while doing it with openBalena since build is done locally

**Comment by pdcastro** [comment]
@lakshaygroverr, the questions below are to help reason about what might be going wrong, and/or to help me try and reproduce the issue. There are some suggestions of things you could try as well:

* What is the full CLI command line you are running?
* What is your device? Is it a Raspberry Pi 3? Pi 4?
* Are you running the CLI on the laptop / development machine, or on the device? The CLI should normally be run on the laptop / development machine, not on the device.
* What is the application's main / default device type? (Output of the command `balena app <appName>`)
* What is the repo and version you're getting balena dash from? Is it [balenalabs/balena-dash](https://github.com/balenalabs/balena-dash) v0.8.5? (`git log` may help you find the version)
* `"Invalid ELF image for this architecture"` means that the selected base image is not compatible with the selected QEMU emulator.
  * In this case, it appears that the relevant base image is 'wpe' (https://github.com/balenalabs/balena-dash/blob/v0.8.5/wpe/Dockerfile#L1), but this depends on the balena dash repo and version.
  * If you're using the `balena deploy <appName>` command, the application's main/default device type (`balena app <appName>`) should be compatible with the base image architecture.
  * An alternative may be to "manually" specify the device type and architecture with the `--deviceType` and `--arch` options to the `balena build` command, e.g.:
`balena build . --deviceType raspberrypi3 --arch armv7hf --emulated`
A list of device types can be obtained with:
`balena devices supported --verbose`
* Even though the CLI should run on the laptop / development machine, the `--dockerHost` and `--dockerPort` can be used to build the images using balenaEngine on the device itself, instead of using Docker on the laptop, thus avoiding the need for QEMU emulation:
  * `balena build . --deviceType raspberrypi3 --arch armv7hf --dockerHost 192.168.0.37 --dockerPort 2375`
Followed by:
`balena deploy <appName> --dockerHost 192.168.0.37 --dockerPort 2375`
  * For this to work, the device should be running a development balenaOS image (see [dev vs prod images](https://www.balena.io/docs/reference/OS/overview/2.x/#development-vs-production-images)), and to avoid conflict with the supervisor, the device should be in [local mode](https://www.balena.io/docs/learn/develop/local-mode/).
* There's no evidence that the version of Node.js is relevant here, but the CLI has been mostly tested with Node versions 8, 10 and 12, and I noticed that you're using Node 13. By the way, are you using the `npm` installation type for the CLI, or a standalone zip file?

Overall this looks like a troubleshooting case rather than a CLI bug, so you may also consider posting to https://forums.balena.io/ where balena support agents may be able help you further.

**Comment by lakshaygroverr** [comment]
Thank for the reply @pdcastro the problem was with the app that was made for Rpi 3(64bit). It worked well when i switched to Rpi3 app , thank you though
