### ISSUE TITLE
[Jetson Nano] `balena local configure`: Error: Unsupported filesystem.

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#1634]
@afitzek reported it for BalenaOS 2.45.1+rev3:
```
> sudo DEBUG=1 ./balena-cli/balena local configure balena.img
Unsupported filesystem.
Error: Unsupported filesystem.
    at /snapshot/versioned-source/node_modules/resin-image-fs/build/driver.js:95:13
    at /snapshot/versioned-source/node_modules/resin-image-fs/build/driver.js:94:64
    at createDriverFromFile (/snapshot/versioned-source/node_modules/resin-image-fs/build/driver.js:93:62)
    at /snapshot/versioned-source/node_modules/resin-image-fs/build/driver.js:137:12
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
    at Object.exports.interact (/snapshot/versioned-source/node_modules/resin-image-fs/build/driver.js:134:6)
    at listDirectory (/snapshot/versioned-source/node_modules/resin-image-fs/build/imagefs.js:365:31)
    at /snapshot/versioned-source/node_modules/resin-image-fs/build/imagefs.js:398:14
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
    at Object.exports.listDirectory (/snapshot/versioned-source/node_modules/resin-image-fs/build/imagefs.js:395:20)
    at prepareConnectionFile (/snapshot/versioned-source/build/actions/local/configure.js:135:18)
    at Command.action (/snapshot/versioned-source/build/actions/local/configure.js:189:12)
    at /snapshot/versioned-source/node_modules/capitano/build/command.js:98:37
    at Command.module.exports.Command.applyPermissions (/snapshot/versioned-source/node_modules/capitano/build/command.js:43:14)
    at Immediate.<anonymous> (/snapshot/versioned-source/node_modules/capitano/build/command.js:92:24)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at runCommand (/snapshot/versioned-source/build/app-capitano.js:181:14)
    at Object.exports.run (/snapshot/versioned-source/build/app-capitano.js:193:39)
    at routeCliFramework (/snapshot/versioned-source/build/preparser.js:39:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1322:13)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
```
> (at)acostach
> (at)afitzek, looks right, the image is a non flasher. has all the partitions at the offsets the nano SPI expects them at. I don't recall changing partitions for this DT between releases

It may or may not be to do with hardcoded (?) partition numbers or offsets. Full discussion:
https://www.flowdock.com/app/rulemotion/r-resinos/threads/rwZud2b2lh8AteFX2Ii8oQL7rI7

**Comment by pdcastro** [comment]
Duplicate of #1632
