### ISSUE TITLE
Balena build with --emulated error, when balena push and build on cloud works perfectly

### ISSUE THREAD

**Issue by Razikus** [balena-io/balena-cli#1649]
- **balena CLI version:** e.g. 11.2.1 (output of the `"balena version"` command)
11.28.11
- **Operating system version:** e.g. Windows 10, Ubuntu 18.04, macOS 10.14.5
Ubuntu 19.10
- **32/64 bit OS and processor:** e.g. 32-bit Windows on 64-bit Intel processor
64 bit Intel
- **Install method:** npm or zip or executable installer
np,
- **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1
Node 10.19.0
np 6.13.4

---

Hello i have a problem with building on emulated environment
I'm using simple service wifi-connect based on balena example
docker-compose.yml:
```
version: "2.1"

services:
    wifi-connect:
        build: ./wifi-connect
        network_mode: "host"
        labels:
            io.balena.features.dbus: '1'
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
```

wifi-connect fork here: https://github.com/Razikus/wifi-connect (just the same as original repo)

Everything is OK when i'm pushing code over balena push (it's builded && working correctly) , but that's not the case for me.

But when i'm using command
balena build --emulated --application Skryba --sources .

It's getting me an error "standard_init_linux.go:211: exec user process caused "exec format error"

```
debug] original argv0="node" argv=[/usr/bin/node,/usr/bin/balena,build,--emulated,--application,Skryba,--sources,.] length=8
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "/home/adam/dev/henk/balena-python-hello-world"
[Debug]   Creating project...
[Info]    Building for rpi/raspberry-pi
[Info]    Emulation is enabled
[Debug]   Found build tasks:.. -
[Debug]       wifi-connect: build [./wifi-connect]
[Debug]   Resolving services with [raspberry-pi|rpi]
[Debug]   Found project types: \
[Debug]       wifi-connect: Dockerfile.template
[Debug]   Prepared tasks; building...
[Build]   Built 1 service in 0:01
[Build]   wifi-connect [======>              ]  33% Step 2/6: standard_init_linux.go:211: exec user process caused "exec format error"
[Error]   Build failed
The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 1
Error: The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 1
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:181:23)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:198:13)
    at Stream.EventEmitter.emit (domain.js:448:20)
    at drain (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/usr/lib/node_modules/balena-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:710:20)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Bluebird.try.then (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:73:20)
    at Builder.createBuildStream (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:72:97)
    at Promise (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/build.js:82:17)
    at Object.runBuildTask (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/build.js:59:12)
    at /usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:158:34
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:4:12)
    at performSingleBuild (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:156:12)
    at Bluebird.map (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:141:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:140:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:5:58)
From previous event:
    at runCommand (/usr/lib/node_modules/balena-cli/build/app-capitano.js:181:14)
    at Object.exports.run (/usr/lib/node_modules/balena-cli/build/app-capitano.js:193:39)
    at routeCliFramework (/usr/lib/node_modules/balena-cli/build/preparser.js:39:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Same output when i specify an arch and deviceType
balena build --emulated --deviceType raspberry-pi --arch rpi
And for this command too:
balena build --emulated --deviceType raspberrypi4-64 --arch aarch64

```
[debug] original argv0="node" argv=[/usr/bin/node,/usr/bin/balena,build,--emulated,--deviceType,raspberry-pi,--arch,rpi] length=8
[Debug]   Parsing input...
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "/home/adam/dev/henk/balena-python-hello-world"
[Debug]   Creating project...
[Info]    Building for rpi/raspberry-pi
[Info]    Emulation is enabled
[Debug]   Found build tasks:.. -
[Debug]       wifi-connect: build [./wifi-connect]
[Debug]   Resolving services with [raspberry-pi|rpi]
[Debug]   Found project types: \
[Debug]       wifi-connect: Dockerfile.template
[Debug]   Prepared tasks; building...
[Build]   Built 1 service in 0:01
[Build]   wifi-connect [======>              ]  33% Step 2/6: standard_init_linux.go:211: exec user process caused "exec format error"
[Error]   Build failed
The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 1
Error: The command '/bin/sh -c install_packages dnsmasq wireless-tools' returned a non-zero code: 1
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:181:23)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at Stream.ondata (internal/streams/legacy.js:15:31)
    at Stream.emit (events.js:198:13)
    at Stream.EventEmitter.emit (domain.js:448:20)
    at drain (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:132:18)
    at Parser.proto.write (/usr/lib/node_modules/balena-cli/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/JSONStream/index.js:23:12)
    at Stream.stream.write (/usr/lib/node_modules/balena-cli/node_modules/through/index.js:26:11)
    at IncomingMessage.ondata (_stream_readable.js:710:20)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:124:22)
    at Socket.socketOnData (_http_client.js:451:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    at Bluebird.try.then (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:73:20)
    at Builder.createBuildStream (/usr/lib/node_modules/balena-cli/node_modules/resin-docker-build/build/builder.js:72:97)
    at Promise (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/build.js:82:17)
    at Object.runBuildTask (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/build.js:59:12)
    at /usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:158:34
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:4:12)
    at performSingleBuild (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:156:12)
    at Bluebird.map (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:141:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
    at Object.<anonymous> (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:140:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/balena-cli/node_modules/resin-multibuild/build/index.js:5:58)
From previous event:
    at runCommand (/usr/lib/node_modules/balena-cli/build/app-capitano.js:181:14)
    at Object.exports.run (/usr/lib/node_modules/balena-cli/build/app-capitano.js:193:39)
    at routeCliFramework (/usr/lib/node_modules/balena-cli/build/preparser.js:39:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/
```

Probably it's not getting properly emulated and using same docker as my host have, but then is the emulated not working?

I can spot these containers on my docker engine with `docker ps --no-trunc -a` along with other containers
```
CONTAINER ID                                                       IMAGE                                                                     COMMAND                                                                           CREATED              STATUS                          PORTS                                            NAMES
aa1906e0224d8b0f3c6e4ea56b6925b283d4356c4caef5f837cc02d3278f3c3e   sha256:19d64471980aa5f2123d7f30f19ba56e3e3919001bdcc800be83489af4e5dcb7   "/bin/sh -c 'install_packages dnsmasq wireless-tools'"                            About a minute ago   Exited (1) About a minute ago                                                    intelligent_moore
1bc16495a073e50c3d0949e1b9beef9d74b2b42c6b0609c5a89be60d9f7e5f30   sha256:c66dfd24a07f43916288aeb2791b1b574041e81bc8382c2470ee85f862a922ea   "/bin/sh -c 'install_packages dnsmasq wireless-tools'"                            About a minute ago   Exited (1) About a minute ago                                                    nervous_lamport
a298c8cbe4c7d0aa296e3c230df54ff186f7b1a6b10a59be7a9f54e8886ac488   sha256:c66dfd24a07f43916288aeb2791b1b574041e81bc8382c2470ee85f862a922ea   "/bin/sh -c 'install_packages dnsmasq wireless-tools'"                            About a minute ago   Exited (1) About a minute ago                                                    gifted_greider
a6ba4cfe3a3d244b7ceba19a3b2c6807d8deb3f60686f350ec0cc7b255a5fbfa   mongo-express                                                             "tini -- /docker-entrypoint.sh mongo-express"
```

**Comment by pdcastro** [comment]
@Razikus, I expect this issue to be fixed in CLI release 11.28.12. (Later today I'll add some test cases to make sure it doesn't happen again; better late than never...) Thank you again for reporting it. 👍
