### ISSUE TITLE
login issue for macOS Mojave

### ISSUE THREAD

**Issue by tyc85** [balena-io/balena-cli#1686]
- **balena CLI version:** e.g. 11.2.1 (output of the `"balena version"` command)
- **Operating system version:** macOS 10.14.6
- **32/64 bit OS and processor:** 64bit macOS 64-bit Intel processor
- **Install method:**  executable installer

---

balena login command not working with the following error message:
- When using web login:
Something went wrong
You couldn't login to the balena CLI for some reason
**on console:**
request to https://api.balena-cloud.com/user/v1/whoami failed, reason: getaddrinfo ENOTFOUND na na:80
Error: request to https://api.balena-cloud.com/user/v1/whoami failed, reason: getaddrinfo ENOTFOUND na na:80
    at Server.server.close (/usr/local/lib/balena-cli/build/auth/server.js:25:28)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at Server.EventEmitter.emit (domain.js:448:20)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Object.exports.awaitForToken (/usr/local/lib/balena-cli/build/auth/server.js:21:12)
    at Object.exports.login (/usr/local/lib/balena-cli/build/auth/index.js:18:19)
From previous event:
    at runCommand (/usr/local/lib/balena-cli/build/app-capitano.js:177:14)
    at Object.exports.run (/usr/local/lib/balena-cli/build/app-capitano.js:189:39)
    at routeCliFramework (/usr/local/lib/balena-cli/build/preparser.js:39:79)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

- When using credentials:
ENOTFOUND: request to https://api.balena-cloud.com/login_ failed, reason: getaddrinfo ENOTFOUND na na:80
FetchError: request to https://api.balena-cloud.com/login_ failed, reason: getaddrinfo ENOTFOUND na na:80
    at ClientRequest.<anonymous> (/usr/local/lib/balena-cli/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at createConnection (/usr/local/lib/balena-cli/node_modules/global-agent/dist/classes/Agent.js:118:17)
    at Socket.socket.on.error (/usr/local/lib/balena-cli/node_modules/global-agent/dist/classes/HttpsProxyAgent.js:28:7)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at new Fetch (/usr/local/lib/balena-cli/node_modules/node-fetch/index.js:49:9)
    at Fetch (/usr/local/lib/balena-cli/node_modules/node-fetch/index.js:37:10)
    at /usr/local/lib/balena-cli/node_modules/fetch-ponyfill/fetch-node.js:15:12
    at requestAsync (/usr/local/lib/balena-cli/node_modules/balena-request/build/utils.js:331:7)
From previous event:
    at requestAsync (/usr/local/lib/balena-cli/node_modules/balena-request/build/utils.js:350:22)
    at /usr/local/lib/balena-cli/node_modules/balena-request/build/utils.js:400:12
    at /usr/local/lib/balena-cli/node_modules/balena-request/build/request.js:184:14
From previous event:
    at Object.exports.send (/usr/local/lib/balena-cli/node_modules/balena-request/build/request.js:183:89)
    at Object.exports.authenticate (/usr/local/lib/balena-cli/node_modules/balena-sdk/build/auth.js:144:20)
    at exports.login (/usr/local/lib/balena-cli/node_modules/balena-sdk/build/auth.js:180:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
From previous event:
    at Object.authenticate (/usr/local/lib/balena-cli/build/utils/patterns.js:28:10)
    at doLogin (/usr/local/lib/balena-cli/build/actions/auth.js:85:33)
    at doLogin (/usr/local/lib/balena-cli/build/actions/auth.js:101:20)/;/';/'

**Comment by pdcastro** [comment]
@tyc85, is the error still happening for you? The `getaddrinfo` error message suggests it was an issue with domain name resolution, which may have been at your end / internet service provider, or at balena's end / AWS data center, and is typically temporary. I have tested the same version of the CLI (11.2.1, executable installer) on the same version of macOS (10.14.6) and I was not able to reproduce it:
```
$ /usr/local/bin/balena version -a
11.2.1
$ /usr/local/bin/balena login
...
Logging in to balena-cloud.com
? How would you like to login? Web authorization (recommended)
Connecting to the web dashboard
Successfully logged in as: gh_paulo_castro
...
$ /usr/local/bin/balena whoami
== ACCOUNT INFORMATION
USERNAME: gh_paulo_castro
EMAIL:    pefcastro@gmail.com
URL:      balena-cloud.com
```
By the way, CLI version 11.2.1 is about 9 months old, and I suggest updating it. See installation options and links in at https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

**Comment by tyc85** [comment]
Hi castro, 
It's still a problem for me on my macOS. Funny thing is that it works on my other macOS 10.14.2 under the same network. 

I did verify NS lookup work well:
$ nslookup api.balena-cloud.com
Server:		192.168.1.254
Address:	192.168.1.254#53

Non-authoritative answer:
api.balena-cloud.com	canonical name = resin-d-alb-15sj6u7hs9afn-1069262607.us-east-1.elb.amazonaws.com.
Name:	resin-d-alb-15sj6u7hs9afn-1069262607.us-east-1.elb.amazonaws.com
Address: 34.235.218.52
Name:	resin-d-alb-15sj6u7hs9afn-1069262607.us-east-1.elb.amazonaws.com
Address: 52.55.68.135

The not working message:

$ /usr/local/bin/balena version -a
balena-cli version "11.30.7"
Node.js version "10.16.0"
====
 /usr/local/bin/balena login
 _            _
| |__   __ _ | |  ____  _ __    __ _
| '_ \ / _` || | / __ \| '_ \  / _` |
| |_) | (_) || ||  ___/| | | || (_) |
|_.__/ \__,_||_| \____/|_| |_| \__,_|


Logging in to balena-cloud.com
? How would you like to login? Credentials
? Email: chent6@corning.com
? Password: [hidden]
ENOTFOUND: request to https://api.balena-cloud.com/login_ failed, reason: getaddrinfo ENOTFOUND na na:80

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, "$env:DEBUG = 1" on
powershell, or "export DEBUG=1" on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

**Comment by pdcastro** [comment]
> It's still a problem for me on my macOS 10.14.6. Funny thing is that it works on my other macOS 10.14.2 under the same network.

Well, that's unexpected. @tyc85, thanks for testing it. Whatever the issue is, it is probably something restricted to that computer (but not necessarily attributable to macOS version 10.14.6, as I am myself running that version without a problem, last rebooted it more than a month ago...) Some thoughts:

* Try the following `curl` command, see if you get an 'OK' response. I know you've already tried the `nslookup` command, but I think that `nslookup` contacts the the name server directly and bypasses the local macOS cache:
```
$ curl api.balena-cloud.com/ping
OK
```

* Try clearing the system DNS cache:
```
$ sudo killall -HUP mDNSResponder; sleep 3;
Password: <macOS login password>
```

* Check that there isn't any proxy configured, including proxy environment variables:
```
$ env | grep -i proxy
# there should be no output, meaning no proxy variables
```

* Check that the output of `balena settings` is more or less similar to mine below:
```
$ balena settings
balenaUrl:            balena-cloud.com
apiUrl:               https://api.balena-cloud.com
vpnUrl:               vpn.balena-cloud.com
registryUrl:          registry.balena-cloud.com
registry2Url:         registry2.balena-cloud.com
imageMakerUrl:        https://img.balena-cloud.com
deltaUrl:             https://delta.balena-cloud.com
dashboardUrl:         https://dashboard.balena-cloud.com
proxyUrl:             balena-devices.com
dataDirectory:        /Users/paulo/.balena
projectsDirectory:    /Users/paulo/BalenaProjects
cacheDirectory:       /Users/paulo/.balena/cache
binDirectory:         /Users/paulo/.balena/bin
imageCacheTime:       604800000
tokenRefreshInterval: 3600000
apiKeyVariable:       BALENA_API_KEY
```

* Now getting desperate... :-) Try rebooting the computer. (macOS is usually very stable and we sometimes may end up not rebooting it for months, but every now and then something may "build up" that gets solved by rebooting.)

**Comment by tyc85** [comment]
Hi Castro, 
   Looks like  
sudo killall -HUP mDNSResponder; sleep 3; 
helps. 
I guess rebooting likely would have worked as well. Thanks for the help.
