### ISSUE TITLE
When doing `balena os initialize` an error is thrown if a drive is not detected.

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#1699]
When doing `balena os initialize` an error is thrown if a drive is not detected (after pressing a key).

```
$ balena os initialize ../pi4.img --type 'raspberrypi4-64'
Initializing device

Note: Initializing the device may ask for administrative permissions
because we need to access the raw devices directly.
x No available drives were detected, plug one in!
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'value' of undefined
    at DynamicList.getCurrentValue (/snapshot/versioned-source/node_modules/inquirer/lib/prompts/list.js:121:53)
    at MapSubscriber._next (/snapshot/versioned-source/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/snapshot/versioned-source/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TakeSubscriber._next (/snapshot/versioned-source/node_modules/rxjs/internal/operators/take.js:54:30)
    at TakeSubscriber.Subscriber.next (/snapshot/versioned-source/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Interface.handler (/snapshot/versioned-source/node_modules/rxjs/internal/observable/fromEvent.js:22:28)
    at Interface.emit (events.js:203:15)
    at Interface.EventEmitter.emit (domain.js:448:20)
    at Interface._onLine (readline.js:308:10)
    at Interface._line (readline.js:656:8)
    at Interface._ttyWrite (readline.js:937:14)
    at ReadStream.onkeypress (readline.js:184:10)
    at ReadStream.emit (events.js:203:15)
    at ReadStream.EventEmitter.emit (domain.js:448:20)
    at emitKeys (internal/readline.js:424:14)
    at emitKeys.next (<anonymous>)
```

---

*Please note that this issue tracker is used for specific bug reports and feature requests.
General and troubleshooting questions are encouraged to be posted to the [balena
forums](https://forums.balena.io), which are monitored by balena's support team and
where the community can both contribute and benefit from the answers.*

*Before submitting this issue please check that this issue is not a duplicate. If there is another
issue describing the same problem or feature please add your information to the existing issue's
comments.*

**Comment by srlowe** [comment]
The symptomns of this bug have change as of v12.55.  Now an error is not thrown, but the prompt hangs after `x No available drives were detected, plug one in!`, and ctrl-c is required to exit.

**Comment by srlowe** [comment]
This appears to be expected behaviour, as process continues if drive is then inserted.
(for ref: https://github.com/balena-io-modules/resin-cli-visuals/blob/87277f849c370f264c641367d3a360a2ba217069/lib/widgets/drive/index.coffee#L45-L66)
