### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/balena-cli/lib' when running cli commands

### ISSUE THREAD

**Issue by szony** [balena-io/balena-cli#1723]
- **balena CLI version:** 11.30.10
- **Operating system version:** MacOS 10.15.3
- **32/64 bit OS and processor:** 64-bit
- **Install method:** MacOS package
- **If npm install, Node.js and npm version:** e.g. Node v8.16.0 and npm v6.4.1

---

I'm using the cli in zsh and frequently I would come across this error when running different commands:

➜  repos balena devices -a tmp0
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: ENOENT: no such file or directory, lstat '/usr/local/lib/balena-cli/lib'
    at Object.realpathSync (fs.js:1461:7)
    at Object.<anonymous> (/usr/local/lib/balena-cli/node_modules/is-installed-globally/index.js:8:29)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at lazy (/usr/local/lib/balena-cli/node_modules/import-lazy/index.js:2:51)
    at /usr/local/lib/balena-cli/node_modules/import-lazy/index.js:10:11
    at UpdateNotifier.notify (/usr/local/lib/balena-cli/node_modules/update-notifier/index.js:122:14)
    at Object.notify (/usr/local/lib/balena-cli/build/utils/update.js:22:18)
    at globalInit (/usr/local/lib/balena-cli/build/app-common.js:148:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)

Typically, second iteration of the same command works just fine. I mainly use balena push, devices, ssh. The error comes up randomly with any of them. The /usr/local/lib/balena-cli/lib file doesn't exist on my system.

**Comment by pdcastro** [comment]
Thanks for reporting it @szony. Apparently it is caused by a bug in an upstream dependency, `sindresorhus/is-installed-globally`, which was also reported (upstream) on Windows:
* https://github.com/sindresorhus/is-installed-globally/issues/4
* https://github.com/sindresorhus/is-installed-globally/issues/6
* https://github.com/sindresorhus/is-installed-globally/pull/7

They claim to have fixed it. I will attempt updating the dependency.

**Comment by pdcastro** [comment]
Fixed in CLI release 11.31.2.
