### ISSUE TITLE
A newline in ~/.balena/token will cause commands to fail

### ISSUE THREAD

**Issue by saintaardvark** [balena-io/balena-cli#1800]
- **balena CLI version:** 11.32.3
- **Operating system version:** eLinux, Fedora 32
- **32/64 bit OS and processor:** 64 bit OS and processor
- **Install method:** zip
- **If npm install, Node.js and npm version:** N/A
---

**Expected behaviour**: A newline at the end of a token should not cause commands to fail.

**Observed behaviour**:  Commands will fail if the token file has a newline:

```
$ export DEBUG=1
$ balena whoami
[debug] original argv0="balena" argv=[/home/hugh/.dotfiles/bin/balena-cli-11.32.3/balena,/snapshot/versioned-source/bin/balena,whoami] length=3
ERR_INVALID_CHAR: Invalid character in header content ["authorization"]
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:473:3)
    at new ClientRequest (_http_client.js:194:14)
    at Object.request (https.js:289:10)
    at Object.<anonymous> (/snapshot/versioned-source/node_modules/@sentry/node/dist/integrations/http.js:65:18)
    at /snapshot/versioned-source/node_modules/agent-base/patch-core.js:25:22
    at Fetch.isRedirect (/snapshot/versioned-source/node_modules/node-fetch/index.js:119:13)
    at new Fetch (/snapshot/versioned-source/node_modules/node-fetch/index.js:49:9)
    at Fetch (/snapshot/versioned-source/node_modules/node-fetch/index.js:37:10)
    at module.exports.fetch.Promise (/snapshot/versioned-source/node_modules/fetch-ponyfill/fetch-node.js:15:12)
    at requestAsync (/snapshot/versioned-source/node_modules/balena-request/build/utils.js:327:7)
```

**Workaround**: Removing the newline makes the `whoami` command work again:

```
# Hexdump shows that the final character is a newline:
$ hexdump -C ~/.balena/token.staging 
00000000  [redacted]
00000010  [redacted]
00000020  0a                                                |.|
00000021
$ truncate -s -1 ~/.balena/token.staging 
$ balena whoami
[debug] original argv0="balena" argv=[/home/hugh/.dotfiles/bin/balena-cli-11.32.3/balena,/snapshot/versioned-source/bin/balena,whoami] length=3
== ACCOUNT INFORMATION
USERNAME: gh_saintaardvark
EMAIL:    aardvark@saintaardvarkthecarpeted.com
URL:      balena-staging.com
```

I'd be happy to work on a PR for this if someone can point me at where the token gets read; I've trolled through the source code a couple of times but haven't been able to find it.

Thanks, and please let me know if you need any further info.

**Comment by pdcastro** [comment]
> I'd be happy to work on a PR for this if someone can point me at where the token gets read

I had never needed to look at that code, but did some digging now. No wonder you couldn't find it, the execution path seems to involve 6 repos/packages. For example for the `balena apps` command:
* https://github.com/balena-io/balena-cli/blob/v11.32.11/lib/app-common.ts#L253
  * → https://github.com/balena-io/balena-sdk/blob/v13.4.1/lib/balena.js#L54-L55
  * → https://github.com/balena-io/balena-sdk/blob/v13.4.1/lib/balena.js#L125-L126
  * → https://github.com/balena-io-modules/balena-auth/blob/v3.0.1/lib/auth.ts#L41
  * → https://github.com/balena-io-modules/balena-settings-storage/blob/master/lib/storage.ts#L43
  * → https://github.com/lmaccherone/node-localstorage/blob/v2.1.5/LocalStorage.coffee#L53
* https://github.com/balena-io/balena-cli/blob/v11.32.11/lib/actions-oclif/apps.ts#L51
  * → https://github.com/balena-io/balena-cli/blob/v11.32.11/lib/command.ts#L104
  * → https://github.com/balena-io/balena-cli/blob/v11.32.11/lib/command.ts#L83
  * → https://github.com/balena-io/balena-cli/blob/v11.32.11/lib/utils/patterns.ts#L82
  * → https://github.com/balena-io/balena-sdk/blob/v13.4.1/lib/auth.ts#L274
  * → https://github.com/balena-io/balena-sdk/blob/v13.4.1/lib/auth.ts#L95
  * → https://github.com/balena-io/balena-sdk/blob/v13.4.1/lib/auth.ts#L77
  * → https://github.com/balena-io-modules/balena-request/blob/master/lib/request.coffee#L173
  * → https://github.com/balena-io-modules/balena-request/blob/master/lib/request.coffee#L52
  * → https://github.com/balena-io-modules/balena-request/blob/master/lib/request.coffee#L77
  * → https://github.com/balena-io-modules/balena-request/blob/master/lib/utils.coffee#L79
* https://github.com/balena-io-modules/balena-auth/blob/v3.0.1/lib/auth.ts#L129
* https://github.com/balena-io-modules/balena-auth/blob/v3.0.1/lib/auth.ts#L205
* https://github.com/balena-io-modules/balena-settings-storage/blob/master/lib/storage.ts#L91
* https://github.com/lmaccherone/node-localstorage/blob/v2.1.5/LocalStorage.coffee#L162

If I got this right, the last bullet point above shows the final actual call to `fs.readFileSync` that reads the token from the `~/.balena/token` file. A newline filter would not be implemented in that repo, though. Perhaps the implementation might fit in the `balena-auth` module, around this line:
https://github.com/balena-io-modules/balena-auth/blob/v3.0.1/lib/auth.ts#L205

Note however that this change would have a wide scope, beyond the CLI, beyond even than the balena SDK, affecting all users of the `balena-request` module which is as generic as making any HTTP requests for any purposes. As it transpires (I hadn't realised it myself), the `~/.balena/token` file is not a "CLI file", it is more of a "balena file" used by the `balena-auth` module and everything downstream. Having said that, the proposed change of ignoring line breaks sounds justifiable, and I am not aware of side effects, assuming that that a token itself cannot contain a line break (not just tokens used by balena-cli, but tokens used by any other packages).

In terms of workarounds, if writing a `bash` script to 'echo' a token, you can use the `echo -n` option, or `printf` as the documentation suggests:
```
$ man echo
     -n    Do not print the trailing newline character.  This may also be achieved
by appending `\c' to the end of the string, as is done by iBCS2 compatible systems.
Note that this option as well as the effect of `\c' are implementation-defined in
IEEE Std 1003.1-2001 (``POSIX.1'') as amended by Cor. 1-2002. Applications aiming
for maximum portability are strongly encouraged to use printf(1) to suppress the
newline character.

     Some shells may provide a builtin echo command which is similar or identical to
this utility.  Most notably, the builtin echo in sh(1) does not accept the -n option.
Consult the builtin(1) manual page.
```

**Comment by pdcastro** [comment]
Connects-to: #1660

**Comment by saintaardvark** [comment]
Wow -- thanks very kindly for the spelunking @pdcastro, I think it would have been very difficult for me to find this on my own. :grinning:
