### ISSUE TITLE
sfdisk: /img/balena.img: does not contain a recognized partition table

### ISSUE THREAD

**Issue by curtiskoelling** [balena-io/balena-cli#1810]
- **balena CLI version:** 11.32.15
- **Operating system version:** Ubuntu 18.04
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** npm Node v8.10.0 and npm v6.10.3

`balena preload balena-cloud-[APP_NAME]-intel-nuc-2.47.1+rev1-v10.6.27.img.zip --splash-image [SPLASH_IMG].png --app [MY_APP_ID] --debug`

**ERROR**
```
Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 811, in <module>
    PARTITIONS_CACHE[None] = prepare_global_partitions()
  File "/usr/src/app/preload.py", line 80, in prepare_global_partitions
    return get_partitions(IMAGE)
  File "/usr/src/app/preload.py", line 69, in get_partitions
    return {p.label: p for p in PartitionTable(image).partitions if p.label}
  File "/usr/src/app/preload.py", line 381, in __init__
    sfdisk("--dump", "--json", image).stdout.decode("utf8")
  File "/usr/lib/python3.6/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/usr/lib/python3.6/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /sbin/sfdisk --dump --json /img/balena.img

  STDOUT:


  STDERR:
sfdisk: /img/balena.img: does not contain a recognized partition table
    at container.wait.then (/usr/local/lib/node_modules/balena-cli/node_modules/balena-preload/lib/preload.js:317:19)
    at tryCatcher (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/balena-cli/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

**Comment by curtiskoelling** [comment]
If I unzip the image file downloaded from the application's page it works. It was unclear to me based on `balena preload --help` that this was the case.

**Comment by pdcastro** [comment]
CLI release 12.44.22 prints a runtime warning message if a zip file is provided, and also catches the error more quickly even if the `--debug` flag is not provided.
