### ISSUE TITLE
Balena Preload broken

### ISSUE THREAD

**Issue by ned-kelly** [balena-io/balena-cli#1922]
Tried multiple times to run balena preload but it's just not working for me.

* Running on linux system with `Docker version 19.03.11, build 42e35e61f3`
* OS: `Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
* Have updated latest balena-cli via npm
* Have cleared all docker images / pruned system
* Running with the following args:

```
balena preload "/opt/balena-cloud-xxxx-PRD-intel-nuc-2.50.1+rev1-v11.4.10-2020-07-07.img" --app 1669116 --splash-image "/opt/xxxx/example.png"
```

I'm just seeing the following:

```
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> 2148f2ac3bcf
Successfully built 2148f2ac3bcf
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 213:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpth_m1mex/docker --host=tcp://0.0.0.0:41287

  STDOUT:


  STDERR:
time="2020-07-07T00:08:55.520018733Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2020-07-07T00:08:55.520731709Z" level=info msg="libcontainerd: started new docker-containerd process" pid=224
time="2020-07-07T00:08:55Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2020-07-07T00:08:55Z" level=info msg="setting subreaper..." module=containerd
time="2020-07-07T00:08:55Z" level=info msg="changing OOM score to -500" module=containerd
time="2020-07-07T00:08:55Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
tim... (4218 more, please see e.stderr)

Traceback (most recent call last):
  File "/usr/src/app/preload.py", line 843, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 802, in get_image_info
    images, supervisor_version = get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 685, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version(inner_image_path)
  File "/usr/src/app/preload.py", line 657, in _get_images_and_supervisor_version
    with docker_context_manager(driver, mountpoint):
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/src/app/preload.py", line 524, in docker_context_manager
    running_dockerd = start_docker_daemon(storage_driver, docker_dir)
  File "/usr/src/app/preload.py", line 493, in start_docker_daemon
    running_dockerd.wait()
  File "/usr/lib/python3.6/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpth_m1mex/docker --host=tcp://0.0.0.0:41287

  STDOUT:


  STDERR:
time="2020-07-07T00:08:55.520018733Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2020-07-07T00:08:55.520731709Z" level=info msg="libcontainerd: started new docker-containerd process" pid=224
time="2020-07-07T00:08:55Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2020-07-07T00:08:55Z" level=info msg="setting subreaper..." module=containerd
time="2020-07-07T00:08:55Z" level=info msg="changing OOM score to -500" module=containerd
time="2020-07-07T00:08:55Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
tim... (4218 more, please see e.stderr)

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/
```

**Comment by pdcastro** [comment]
@ned-kelly, thank you for reporting this issue. I am setting up a Debian VM with Docker v19.03.11 in order to try and reproduce the issue (I was not able to reproduce it with what I had at hand: Ubuntu 18.04, Docker 18.09.7, balena CLI v12.6.0 and Node v12.18.2). Meanwhile, would you be able to confirm the version of Debian (10 - Buster?), CLI (also v12.6.0?) and Node that you were using?

**Comment by pdcastro** [comment]
I was unable to reproduce it with Debian 10 and Docker 19.03:
```
paulo@debian:~$ cat /etc/issue
Debian GNU/Linux 10 \n \l

paulo@debian:~$ uname -a
Linux debian 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

paulo@debian:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.12
...
Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
...

paulo@debian:~$ which balena
/home/paulo/.nvm/versions/node/v12.18.2/bin/balena

paulo@debian:~$ balena version -a
balena-cli version "12.6.0"
Node.js version "12.18.2"

paulo@debian:~$ balena preload "Downloads/balena-cloud-test-nuc-intel-nuc-2.50.1+rev1-v11.4.10.img" --app test-nuc --splash-image "Downloads/resinio.png" --commit current
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting balena settings
| Checking if the image is an edison zip archive
/ Creating preloader container
- Starting preloader container
\ Fetching application test-nuc
/ Reading image information
\ Resizing partitions and waiting for dockerd to start
Pulling 1 image [========================] 100%
- Cleaning up temporary files
```

Looking at the error message you were getting:
```
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpth_m1mex/docker --host=tcp://0.0.0.0:41287

  STDERR:
time="2020-07-07T00:08:55.520018733Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2020-07-07T00:08:55.520731709Z" level=info msg="libcontainerd: started new docker-containerd process" pid=224
time="2020-07-07T00:08:55Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2020-07-07T00:08:55Z" level=info msg="setting subreaper..." module=containerd
time="2020-07-07T00:08:55Z" level=info msg="changing OOM score to -500" module=containerd
time="2020-07-07T00:08:55Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
(4218 more, please see e.stderr)
```

We see that the error happened in starting `/usr/local/bin/dockerd` (exit code 1), and that the stderr output (that might have revealed the problem) was unfortunately truncated.

Suggestions:
* Set a DEBUG=1 environment variable:
```
DEBUG=1 balena preload "/opt/balena-cloud-xxxx-PRD-intel-nuc-2.50.1+rev1-v11.4.10-2020-07-07.img" --app 1669116 --splash-image "/opt/xxxx/example.png"
```
* May sound silly, but... try restarting the computer.
* I will look at code changes to try and capture more of the stderr output that was truncated.

**Comment by ned-kelly** [comment]
Thanks @pdcastro 

* AUFS support is loaded - sorry already checked & forgot to mention that in original post
* Debian GNU/Linux 10 (buster)
* `balena-cli@12.5.2`
* Node `v12.18.0`

exporting `DEBUG=1` is not showing any more verbose logs ... The STDERR is still being truncated.

Cheers,

**Comment by pdcastro** [comment]
@ned-kelly, CLI release v12.6.1 (or later) should now print the full stderr output of `dockerd`, thus hopefully revealing what the underlying issue is. (I still couldn't reproduce the error over here, even with CLI 12.5.2, Node 12.18.0, Debian 10.4.) As you had mentioned that the CLI was being installed via the `npm` method, in case you're installing it as the `root` user (not recommended), be sure to add the `--unsafe-perm` flag so that the patches can be applied. Look for the `balena-preload@9.0.0` patch, as shown below:
```
$ npm install balena-cli -g --production --unsafe-perm
...
> patch-package --patch-dir patches0 && patch-package
patch-package 6.2.2
Applying patches...
...
balena-preload@9.0.0 ✔
...
```
You could also use a standalone zip package instead of the npm installation. Installation options are documented at:
https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

Note that the truncated stderr output will still be printed _in addition_ to the full stderr output. So when you see a truncated output and something like `(4218 more, please see e.stderr)`, don't despair! :-) Look for additional output around it (I think the full output is printed _before/above_ the truncated output, starting with a line that reads `An error has occurred executing 'dockerd':`).

**Comment by ned-kelly** [comment]
Hi @pdcastro - so here's a quick update:

* Removed ALL node modules from `/usr/local/lib/node_modules`
* Stopped Docker & Emptied `/tmp` directory
*  Re-installed with `npm install balena-cli -g --production --unsafe-perm` - 
    * balena-cli@12.6.4 now installed
* Still receiving errors - Here's the output of `export DEBUG=1 && balena preload .....`

```
Error: Step 1/7 : FROM docker:17.12.0-ce-dind
 ---> 08c245f2381e
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs util-linux sfdisk file coreutils sgdisk
 ---> Using cache
 ---> 5a9e67ca2a62
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
 ---> 3007baa93bd6
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
 ---> c72508422ac6
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
 ---> 6a3a7115220b
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 6a232f9a4c0f
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> 942c1572db36
Successfully built 942c1572db36
Successfully tagged balena/balena-preload:latest
Waiting for Docker to start...
Exception in thread background thread for pid 217:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 1540, in wrap
    fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2459, in background_thread
    handle_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 2157, in fn
    return self.command.handle_command_exit_code(exit_code)
  File "/usr/lib/python3.6/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1:

  RAN: /usr/local/bin/dockerd --storage-driver=aufs --data-root=/tmp/tmpayjeo88k/docker --host=tcp://0.0.0.0:44591

  STDOUT:


  STDERR:
time="2020-07-08T23:04:33.792505217Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2020-07-08T23:04:33.803914100Z" level=info msg="libcontainerd: started new docker-containerd process" pid=227
time="2020-07-08T23:04:33Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2020-07-08T23:04:33Z" level=info msg="setting subreaper..." module=containerd
time="2020-07-08T23:04:33Z" level=info msg="changing OOM score to -500" module=containerd
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
tim... (4218 more, please see e.stderr)

An error has occurred executing 'dockerd':
time="2020-07-08T23:04:33.792505217Z" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
time="2020-07-08T23:04:33.803914100Z" level=info msg="libcontainerd: started new docker-containerd process" pid=227
time="2020-07-08T23:04:33Z" level=info msg="starting containerd" module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
time="2020-07-08T23:04:33Z" level=info msg="setting subreaper..." module=containerd
time="2020-07-08T23:04:33Z" level=info msg="changing OOM score to -500" module=containerd
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.content.v1.content"..." module=containerd type=io.containerd.content.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." module=containerd type=io.containerd.snapshotter.v1
time="2020-07-08T23:04:33Z" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /tmp/tmpayjeo88k/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." module=containerd type=io.containerd.snapshotter.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." module=containerd type=io.containerd.metadata.v1
time="2020-07-08T23:04:33Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /tmp/tmpayjeo88k/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." module=containerd type=io.containerd.differ.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." module=containerd type=io.containerd.gc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." module=containerd type=io.containerd.monitor.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." module=containerd type=io.containerd.runtime.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." module=containerd type=io.containerd.grpc.v1
time="2020-07-08T23:04:33Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd-debug.sock" module="containerd/debug"
time="2020-07-08T23:04:33Z" level=info msg=serving... address="/var/run/docker/containerd/docker-containerd.sock" module="containerd/grpc"
time="2020-07-08T23:04:33Z" level=info msg="containerd successfully booted in 0.015406s" module=containerd
time="2020-07-08T23:04:33.852294553Z" level=warning msg="failed to rename /tmp/tmpayjeo88k/docker/tmp for background deletion: rename /tmp/tmpayjeo88k/docker/tmp /tmp/tmpayjeo88k/docker/tmp-old: structure needs cleaning. Deleting synchronously"
time="2020-07-08T23:04:33.856890209Z" level=warning msg="failed to delete old tmp directory: /tmp/tmpayjeo88k/docker/tmp"
Error starting daemon: Unable to get the TempDir under /tmp/tmpayjeo88k/docker: mkdir /tmp/tmpayjeo88k/docker/tmp: structure needs cleaning
```

Let me know if any of this will help further debug the problem.

Cheers,

**Comment by pdcastro** [comment]
@ned-kelly, thanks, the good news is that the extra stderr output has worked! :-)  So the key errors we are dealing with are:
```
time="2020-07-08T23:04:33.852294553Z" level=warning
  msg="failed to rename /tmp/tmpayjeo88k/docker/tmp for background deletion:
  rename /tmp/tmpayjeo88k/docker/tmp /tmp/tmpayjeo88k/docker/tmp-old:
  structure needs cleaning. Deleting synchronously"

time="2020-07-08T23:04:33.856890209Z" level=warning
  msg="failed to delete old tmp directory: /tmp/tmpayjeo88k/docker/tmp"

Error starting daemon: Unable to get the TempDir under /tmp/tmpayjeo88k/docker:
  mkdir /tmp/tmpayjeo88k/docker/tmp: structure needs cleaning
```

I believe that the `/tmp` folder in question is not in the host OS (Debian), rather a `/tmp` folder inside a Docker container that `balena preload` creates behind the scenes in order to perform the preloading. Probably a container based on one of these Docker images:
```
$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
balena/balena-preload   latest              836f1eb11c5c        26 hours ago        196MB
docker                  17.12.0-ce-dind     08c245f2381e        2 years ago         126MB
```
Containers such as:
```
$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS                       PORTS               NAMES
08dd90aa36c0        balena/balena-preload   "dockerd-entrypoint.…"   6 minutes ago        Exited (0) 5 minutes ago                         elated_elgamal
b013bacd3394        balena/balena-preload   "dockerd-entrypoint.…"   6 minutes ago        Exited (127) 6 minutes ago                       gracious_benz
```
I am thinking that, somehow, an image or container got into filesystem corruption or even lack of disk space, and I suggest deleting these containers / images, then re-executing `balena preload` (which will cause the images to be re-downloaded as needed). You can selectively delete the containers / images, then also run `docker system prune` to remove unused intermediate images. Or, you can even delete all images and containers, with commands such as ([reference](https://stackoverflow.com/questions/44785585/how-to-delete-all-docker-local-docker-images)):
```
$ docker rm -vf $(docker ps -aq)

$ docker rmi -f $(docker images -aq)
```

Hopefully this will solve the issue. If not... Something else I'd suggest is checking that the installation of Docker on Debian was really successful, including the "post-install steps" as documented by Docker:
* [Install Docker Engine on Debian: Install using the repository](https://docs.docker.com/engine/install/debian/#install-using-the-repository)
* [Post-installation steps for Linux](https://docs.docker.com/engine/install/linux-postinstall/)

**Comment by ned-kelly** [comment]
Hi @pdcastro,

So after pruning the system, and removing all docker images the problem still persists...
Nothing wrong with docker - I'm running other containers fine with no worries.

Furthermore this is not a new system - i was previously using the balena-cli to pre-load without any issues which is odd.

**Comment by pdcastro** [comment]
A Google search for ["structure needs cleaning"](https://www.google.com/search?q=%22structure+needs+cleaning%22), which appears to be the key error preventing things from working, suggests that it is indicative of filesystem corruption. At first I though that the filesystem corruption would be inside a Docker container, but it could also be on the host OS itself. So perhaps run [fsck](https://www.google.com/search?q=linux+fsck) or similar. 🤔
