### ISSUE TITLE
`balena device` :  Cannot read property 'commit' of undefined

### ISSUE THREAD

**Issue by srlowe** [balena-io/balena-cli#2024]
Reported by @xginn8 , device is in local mode.
```
/tmp/work
❯ balena --version                                     
12.16.0

/tmp/work
❯ balena device e655ba756a2730f5a737748a48bab990 

Cannot read property 'commit' of undefined

Additional information may be available with the `--debug` flag.
For help, visit our support forums: https://forums.balena.io
For bug reports or feature requests, see: https://github.com/balena-io/balena-cli/issues/

❯ balena device e655ba756a2730f5a737748a48bab990 --debug
[debug] new argv=[/usr/bin/node,/bin/balena,device,e655ba756a2730f5a737748a48bab990] length=4
Cannot read property 'commit' of undefined

TypeError: Cannot read property 'commit' of undefined
    at DeviceCmd.run (/usr/lib/node_modules/balena-cli/build/actions-oclif/device/index.js:45:55)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by srlowe** [comment]
Was able to reproduce by creating a new application, then moving an existing device to it, and running `balena device`.
