### ISSUE TITLE
RangeError: Maximum call stack size exceeded (@sentry/node/dist/integrations/console.js)

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2060]
```
$ balena push 192.168.1.149 -m
...
[Build]   [main] Removing intermediate container 4612f12b4ac1
[Build]   [main]  ---> 7dedd168ac81
[Build]   [main] Successfully built 7dedd168ac81
[Build]   [main] Successfully tagged local_image_main:latest
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
RangeError: Maximum call stack size exceeded
    at Object.error (/snapshot/balena-cli/node_modules/@sentry/node/dist/integrations/console.js:72:36)
    at Object.printErrorMessage (/snapshot/balena-cli/build/errors.js:140:13)
    at Object.handleError (/snapshot/balena-cli/build/errors.js:122:17)
    at Object.run (/snapshot/balena-cli/build/app-oclif.js:34:73)
    at async Object.run (/snapshot/balena-cli/build/app.js:17:5)
The terminal process "/bin/bash '-c', 'balena push 192.168.1.149 -m'" terminated with exit code: 1.
```

Originally reported at: https://www.flowdock.com/app/rulemotion/i-cli/threads/NDIXJP3vrEsNHSz57tuO9UneDNw

**Comment by pdcastro** [comment]
This issue is understood to have been fixed in CLI release v12.25.0 (PR #2061).
