### ISSUE TITLE
balena deploy --build : Payload Too Large

### ISSUE THREAD

**Issue by pdcastro** [balena-io/balena-cli#2086]
Originally reported in internal / private thread:
https://www.flowdock.com/app/rulemotion/r-beginners/threads/hGEdcyUYgfWA29LAW-Rb3mGqsnF

```
[Build]   main Successfully built 6d7...
[Build]   main Successfully tagged br-cam_main:latest
[Build]   main Image size: 3.69 MB
[Build]   Built 1 service in 33:47
[Info]    Creating release...
[Debug]   Tagging images...
[Debug]   Authorizing push...
[Debug]   Requesting access to previously pushed image repo (v2/e38...)
[Info]    Pushing images to registry...
[Debug]   Saving image registry2.balena-cloud.com/v2/0fc...
[Debug]   Untagging images...
[Info]    Saving release...
[Error]   Deploy failed
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Payload Too Large</pre>
</body>
</html>

HttpResponseError: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Payload Too Large</pre>
</body>
</html>

    at wrapResponseError (/usr/lib/node_modules/balena-cli/node_modules/balena-release/build/models.js:59:19)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /usr/lib/node_modules/balena-cli/build/utils/compose_ts.js:668:9
    at async Promise.all (index 0)
From previous event:
    at processImmediate (node:internal/timers:462:21)
From previous event:
    at exports.pushAndUpdateServiceImages (/usr/lib/node_modules/balena-cli/build/utils/compose.js:224:21)
    at pushServiceImages (/usr/lib/node_modules/balena-cli/build/utils/compose_ts.js:663:11)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async deployProject (/usr/lib/node_modules/balena-cli/build/utils/compose_ts.js:691:13)
    at async DeployCmd.deployProject (/usr/lib/node_modules/balena-cli/build/commands/deploy.js:139:27)
    at async DeployCmd.run (/usr/lib/node_modules/balena-cli/build/commands/deploy.js:44:9)
    at async DeployCmd._run (/usr/lib/node_modules/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/lib/node_modules/balena-cli/node_modules/@oclif/config/lib/config.js:175:24)
    at async CustomMain.run (/usr/lib/node_modules/balena-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async CustomMain._run (/usr/lib/node_modules/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Promise.all (index 1)
    at async oclifRun (/usr/lib/node_modules/balena-cli/build/app.js:75:5)
    at async Object.run (/usr/lib/node_modules/balena-cli/build/app.js:88:9)
```

Possibly going back to: https://forums.balena.io/t/payload-too-large/2750

In some way, probably related or similar to:
* https://github.com/balena-io/balena-builder/issues/173
* https://github.com/balena-io/balena-builder/pull/531
* https://github.com/balena-io/balena-builder/pull/619

**Comment by pdcastro** [comment]
Somewhat related issue, involving `balena push` instead of `balena deploy`: #2065

**Comment by klutchell** [comment]
This builder change is also related:
- https://github.com/balena-io/balena-builder/pull/540

**Comment by pdcastro** [comment]
Assuming that this issue has a similar cause as another issue observed in the past with `balena push`, a workaround is to redirect verbose output to files in Dockerfile RUN instructions. Example:

Before:
```
RUN make app.c
```
After:
```
RUN make app.c > make-logs.txt
```
Another workaround may be to run `balena build` and `balena deploy` in separate steps, instead of `balena deploy --build`.

**Comment by pdcastro** [comment]
> Alternatively, run `balena build` and `balena deploy` in separate steps
>> Why would running these as separate steps work instead, surely it's still handling the same size payload?

The payload in question is not the built image, it's the build logs: the text output of `balena build` or `balena deploy --build` printed to the console. Dockerfile RUN instructions of compilation steps using "make" or "pip install" or "npm install" sometimes produce a lot of build log output, potentially megabytes. The build logs (when produced) can be seen in the balenaCloud web dashboard Releases page for a fleet. When `balena build` and `balena deploy` are used separately, the build logs are lost: only shown on the developer's workstation console and not uploaded to the cloud. When `balena deploy --build` (plus maybe `--nocache`) is used, the build logs are uploaded to the cloud and may thus produce the Payload Too Large error.

**Comment by pdcastro** [comment]
Additional findings from an [FD thread](https://www.flowdock.com/app/rulemotion/i-cli/threads/iHZVH6VOF7oNvh-Qg3HiVv1rW5c) (restricted access):

`balena-builder` has code to truncate the logs for releases created through the `git push` and `balena push` workflows:
https://github.com/balena-io/balena-builder/blob/v8.7.2/src/api/utils.ts#L22-L50 (restricted access)

However I have not found similar code for the `balena deploy` workflow. I understand that the `Payload Too Large` error is throw at either the `api.post` or `api.patch` lines at:
* https://github.com/balena-io-modules/balena-release/blob/v3.2.0/src/models.ts#L121
* https://github.com/balena-io-modules/balena-release/blob/v3.2.0/src/models.ts#L130

Which are called from:
https://github.com/balena-io/balena-cli/blob/v13.1.13/lib/utils/compose_ts.ts#L1343-L1346

I think the best place to insert the truncation would be the [balena-release](https://github.com/balena-io-modules/balena-release) repo, because it then solves the problem for any downstream users of `balena-release` including `balena-cli`.
