### ISSUE TITLE
Image name mismatch error

### ISSUE THREAD

**Issue by joshbwlng** [balena-io/balena-cli#2103]
# Expected Behavior

Should be able to be build and deploy services to local-mode devices that have both `image` and `build` defined in `docker-compose.yml`.

# Actual Behavior

An issue with expected image names results in this repeated output from balena-cli:
```
...
[Logs]    [11/26/2020, 4:41:34 PM] Installing service 'tick local_image_tick:latest'
[Logs]    [11/26/2020, 4:41:34 PM] Installing service 'worker_1 local_image_worker_1:latest'
[Logs]    [11/26/2020, 4:41:34 PM] Installing service 'worker_2 local_image_worker_2:latest'
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Logs]    [11/26/2020, 4:41:50 PM] Installing service 'tick local_image_tick:latest'
[Logs]    [11/26/2020, 4:41:50 PM] Installing service 'worker_1 local_image_worker_1:latest'
[Logs]    [11/26/2020, 4:41:50 PM] Installing service 'worker_2 local_image_worker_2:latest'
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
[Debug]   Device state not settled, retrying in 1000ms
...
```

And these errors from `balena.service` in the device:
```
...
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":8,"serviceName":"worker_2","releaseId":1}}
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":7,"serviceName":"worker_1","releaseId":1}}
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]   Scheduling another update attempt in 1000ms due to failure:  Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_worker_2:latest  Steps:["start","start","start"]
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]         at /usr/src/app/dist/app.js:2:2958395
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]       at runNextTicks (internal/process/task_queues.js:62:5)
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]       at processImmediate (internal/timers.js:429:9)
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":5,"serviceName":"tick","releaseId":1}}
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]   Device state apply error Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_worker_2:latest  Steps:["start","start","start"]
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]         at /usr/src/app/dist/app.js:2:2958395
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]       at runNextTicks (internal/process/task_queues.js:62:5)
Nov 26 07:42:59 localhost.localdomain c6badebdcb08[1141]: [error]       at processImmediate (internal/timers.js:429:9)
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [info]    Applying target state
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":5,"serviceName":"tick","releaseId":1}}
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":7,"serviceName":"worker_1","releaseId":1}}
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [event]   Event: Service install {"service":{"appId":1,"serviceId":8,"serviceName":"worker_2","releaseId":1}}
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [error]   Updating failed, but there's another update scheduled immediately:  Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_tick:latest  Steps:["start","start","start"]
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [error]         at /usr/src/app/dist/app.js:2:2958395
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [error]   Device state apply error Error: Failed to apply state transition steps. (HTTP code 404) no such container - No such image: local_image_tick:latest  Steps:["start","start","start"]
Nov 26 07:43:00 localhost.localdomain c6badebdcb08[1141]: [error]         at /usr/src/app/dist/app.js:2:2958395
...
```

# Steps to Reproduce the Problem

Example service definition:
```
version: '2.1'

services:
  tick:
    image: my-org/some-tick-image
    build:
      context: .
      dockerfile: apps/my-app/Dockerfile
    restart: always
    networks:
      - internal

networks:
  internal: {}
```

`balena push`ing this to a local-mode device should result in the above errors.

# Specifications

- **balena CLI version:** 12.28.2
- **Cloud backend:** balenaCloud (but livepushing directly to local-mode device)
- **Operating system version:** Arch Linux
- **32/64 bit OS and processor:** 64-bit Intel processor
- **Install method:** zip package

# Additional References
https://www.flowdock.com/app/rulemotion/r-beginners/threads/FbJ9LRMrYFmsoo5AEEqiWBzYcLD

**Comment by pdcastro** [comment]
Sounds like a duplicate of #1874 [Use of 'build' and 'image' config options together when using compose file prevents containers launching under local push](https://github.com/balena-io/balena-cli/issues/1874)

**Comment by joshbwlng** [comment]
@pdcastro I think you're right, I'll close this and post my logs in that issue!
