### ISSUE TITLE
Fix for NodeJS>13.0.0?

### ISSUE THREAD

**Issue by brainstorm** [balena-io/balena-cli#2219]
```
$ git clone https://github.com/balena-io/balena-cli && cd balena-cli && npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'balena-cli@12.41.1',
npm WARN EBADENGINE   required: { node: '>=10.20.0 <13.0.0' },
npm WARN EBADENGINE   current: { node: 'v15.11.0', npm: '7.6.0' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /opt/homebrew/Cellar/node/15.11.0/bin/node /opt/homebrew/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/Users/rvalls/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! > resin-discoverable-services@1.2.2 prepublish
npm ERR! > npm test && npm run build
npm ERR!
npm ERR!
npm ERR! > resin-discoverable-services@1.2.2 test
npm ERR! > npm run lint && gulp test
npm ERR!
npm ERR!
npm ERR! > resin-discoverable-services@1.2.2 lint
npm ERR! > resin-lint lib tests gulpfile.coffee
npm ERR!
npm ERR!   ⚡ lib/discoverable.coffee
npm ERR!      ⚡ #345: Variable "publishedServices" is assigned to but never read.
npm ERR!   ⚡ tests/discovery.spec.coffee
npm ERR!      ⚡ #11: Variable "be" is assigned to but never read.
npm ERR!   ✓ gulpfile.coffee
npm ERR!
npm ERR! ⚡ Warning! » 0 errors and 2 warnings in 3 files
npm ERR!
npm ERR! [14:08:02] Requiring external module coffeescript/register
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN Found: chai@3.5.0
npm ERR! npm WARN node_modules/chai
npm ERR! npm WARN   dev chai@"^3.5.0" from the root project
npm ERR! npm WARN   4 more (chai-as-promised, mochainon, chai-as-promised, chai-datetime)
npm ERR! npm WARN
npm ERR! npm WARN Could not resolve dependency:
npm ERR! npm WARN peer chai@"^4.1.2" from chai-string@1.5.0
npm ERR! npm WARN node_modules/chai-string
npm ERR! npm WARN   chai-string@"^1.1.2" from mochainon@1.0.0
npm ERR! npm WARN   node_modules/mochainon
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm ERR! npm WARN deprecated coffee-script@1.11.1: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated samsam@1.1.2: This package has been deprecated in favour of @sinonjs/samsam
npm ERR! npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm ERR! npm WARN deprecated json3@3.3.2: Please use the native JSON object instead of JSON 3
npm ERR! npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated resin-lint@1.5.7: resin-lint is deprecated, please use @balena/lint instead
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! fs.js:51
npm ERR! } = primordials;
npm ERR!     ^
npm ERR!
npm ERR! ReferenceError: primordials is not defined
npm ERR!     at fs.js:51:5
npm ERR!     at req_ (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/natives/index.js:143:24)
npm ERR!     at Object.req [as require] (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/natives/index.js:55:10)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/graceful-fs/fs.js:1:37)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/graceful-fs/graceful-fs.js:3:27)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/vinyl-fs/lib/src/index.js:8:19)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/vinyl-fs/index.js:4:8)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/gulp/index.js:7:11)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/gulpfile.coffee:1:8)
npm ERR!     at Object.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/gulpfile.coffee:1:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1092:14)
npm ERR!     at Object.loadFile (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:16:19)
npm ERR!     at Module.load (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:996:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:92:18)
npm ERR!     at Liftoff.handleArguments (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/gulp/bin/gulp.js:116:3)
npm ERR!     at Liftoff.execute (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/liftoff/index.js:203:12)
npm ERR!     at module.exports (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/flagged-respawn/index.js:51:3)
npm ERR!     at Liftoff.<anonymous> (/Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/liftoff/index.js:195:5)
npm ERR!     at /Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/liftoff/index.js:165:9
npm ERR!     at /Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767/node_modules/v8flags/index.js:93:14
npm ERR!     at FSReqCallback.oncomplete (node:fs:190:23)
npm ERR!
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /Users/rvalls/.npm/_cacache/tmp/git-clone-02bdf767
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c npm test && npm run build
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/rvalls/.npm/_logs/2021-03-17T03_08_02_274Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rvalls/.npm/_logs/2021-03-17T03_08_04_848Z-debug.log
```

**Comment by brainstorm** [comment]
Also, there seem to be no working Apple M1 silicon builds as bottles for Homebrew, unfortunately:

```
% brew install balena-cli
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
Updated 1 cask.

Error: balena-cli: no bottle available!
You can try to install from source with:
  brew install --build-from-source balena-cli
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```

And `brew install --build-from-source balena-cli` results in the same error as above.

**Comment by brainstorm** [comment]
Same goes for Balena Engine:

```
 % curl -sfL https://balena.io/engine/install.sh | sh
Unknown machine type: arm64
```

:__(
