### ISSUE TITLE
docker-compose.dev.yml causes volumes to become invalid

### ISSUE THREAD

**Issue by sgrimm** [balena-io/balena-cli#2226]
# Expected Behavior

Creating a `docker-compose.dev.yml` file with a service definition overrides that service's definition but has no impact on the rest of the project as defined in `docker-compose.yml`.

# Actual Behavior

If `docker-compose.yml` has a `volumes` section with a volume called `chromium-settings` and the local device's IP address is 192.168.1.73, `balena push 192.168.1.73` bombs out with an error:

```
data/volumes/chromium-settings should be object,null
```

Output when I add `--debug`:

```
[Debug]   Using build source directory: . 
[Debug]   Pushing to local device: 192.168.1.73
[Debug]   Checking we can access device
[Debug]   Sending request to http://192.168.1.73:48484/ping
[Debug]   Checking device supervisor version: 12.4.3
[Info]    Starting build on device 192.168.1.73
[Debug]   Loading project...
[Debug]   Resolving project...
[Debug]   docker-compose.yml file found at "."
[Info]    Docker compose dev overlay detected (docker-compose.dev.yml) - merging.
[Debug]   Creating project...
data/volumes/chromium-settings should be object,null

ValidationError: data/volumes/chromium-settings should be object,null
    at Object.normalize (/usr/local/lib/balena-cli/node_modules/resin-compose-parse/build/compose.js:77:19)
    at createProject (/usr/local/lib/balena-cli/build/utils/compose.js:30:33)
    at Object.loadProject (/usr/local/lib/balena-cli/build/utils/compose_ts.js:79:12)
    at async Object.deployToDevice (/usr/local/lib/balena-cli/build/utils/device/deploy.js:97:21)
    at async PushCmd.pushToDevice (/usr/local/lib/balena-cli/build/commands/push.js:94:13)
    at async PushCmd.run (/usr/local/lib/balena-cli/build/commands/push.js:37:17)
    at async PushCmd._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/balena-cli/node_modules/@oclif/config/lib/config.js:175:24)
    at async CustomMain.run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async CustomMain._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Promise.all (index 1)
    at async oclifRun (/usr/local/lib/balena-cli/build/app.js:75:5)
    at async Object.run (/usr/local/lib/balena-cli/build/app.js:88:9)
```

# Steps to Reproduce the Problem

Minimal `docker-compose.yml`:

```yaml
version: '2'

volumes:
  chromium-settings:

services:
  chromium:
    image: balenablocks/browser:raspberrypi4-64
    volumes:
      - 'chromium-settings:/data'
```

And `docker-compose.dev.yml`:

```yaml
services:
  dummy:
    image: "xyz"
```

Put a device in local mode and run `balena push <ip-address>` and you'll see the error.

# Specifications

- **balena CLI version:** balena-cli version "12.42.0" Node.js version "12.20.0"
- **Cloud backend: openBalena or balenaCloud?** balenaCloud
- **Operating system version:** macOS 10.15.7
- **32/64 bit OS and processor:** 64-bit OS on 64-bit processor
- **Install method:** pkg file from GitHub

# Additional References

I edited `compose_ts.js` to output the offending compose YAML.

```
[Debug]   version: '2'
[Debug]   volumes:
[Debug]     chromium-settings: null
[Debug]   services:
[Debug]     chromium:
[Debug]       image: 'balenablocks/browser:raspberrypi4-64'
[Debug]       volumes:
[Debug]         - 'chromium-settings:/data'
[Debug]     dummy:
[Debug]       image: xyz
data/volumes/chromium-settings should be object,null

ValidationError: data/volumes/chromium-settings should be object,null
...same stack trace as above...
```

**Comment by pdcastro** [comment]
Thank you for reporting this issue! It was resolved in CLI version 12.42.2.
