### ISSUE TITLE
balena local configure fails when resin-wifi is not available on the image

### ISSUE THREAD

**Issue by pipex** [balena-io/balena-cli#2239]
# Expected Behavior

Expected to see a prompt to configure network ssid

```
sudo balena local configure balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img
? Network SSID  (My_WiFi_Ssid) %
```

# Actual Behavior

```
sudo balena local configure --debug balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img
[debug] new argv=[/usr/local/lib/balena-cli/bin/node,/usr/local/lib/balena-cli/bin/run,local:configure,balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img] length=4
ERR_INVALID_ARG_TYPE: The "original" argument must be of type function. Received undefined

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function. Received undefined
    at Object.promisify (internal/util.js:279:11)
    at /usr/local/lib/balena-cli/build/commands/local/configure.js:178:37
    at runInFat (/usr/local/lib/balena-cli/node_modules/balena-image-fs/build/index.js:62:18)
    at async tryInteract (/usr/local/lib/balena-cli/node_modules/balena-image-fs/build/index.js:81:16)
    at async diskInteract (/usr/local/lib/balena-cli/node_modules/balena-image-fs/build/index.js:109:12)
    at async /usr/local/lib/balena-cli/node_modules/balena-image-fs/build/index.js:126:20
    at async Object.withOpenFile (/usr/local/lib/balena-cli/node_modules/file-disk/build/index.js:106:16)
    at async Object.interact (/usr/local/lib/balena-cli/node_modules/balena-image-fs/build/index.js:124:16)
    at async LocalConfigureCmd.prepareConnectionFile (/usr/local/lib/balena-cli/build/commands/local/configure.js:177:13)
    at async LocalConfigureCmd.run (/usr/local/lib/balena-cli/build/commands/local/configure.js:92:37)
    at async LocalConfigureCmd._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/usr/local/lib/balena-cli/node_modules/@oclif/config/lib/config.js:175:24)
    at async CustomMain.run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/main.js:27:9)
    at async CustomMain._run (/usr/local/lib/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Promise.all (index 1)
    at async oclifRun (/usr/local/lib/balena-cli/build/app.js:75:5)

For further help or support, visit:
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting
```

# Steps to Reproduce the Problem

This happens when the `resin-wifi` file is not available on the image

1. Download an image from balenaCloud or from https://www.balena.io/os/#download. I tested with balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img
2. Unpack the image `unzip balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img.zip`
3. If the image is from balenaCloud, mount the image and remove `resin-wifi` from the `system-connections` folder
4. Unmount the image and do `balena local configure balena-cloud-raspberrypi3-64-2.65.0+rev1-dev-v12.2.11.img`

The issue appears to be in [this line](https://github.com/balena-io/balena-cli/blob/master/lib/commands/local/configure.ts#L272), apparently `_fs.copyFile` is not a valid function.

# Specifications

- balena-cli version "12.44.1"
- Node.js version "12.20.0"
- macOS 11.2.1
- 64 bit processor
- Installed from .pkg

**Comment by pipex** [comment]
The workaround for now is to mount the image and copy `system-connections/resin-sample.ignore` to `system-connections/resin-wifi`

**Comment by klutchell** [comment]
Issue does not appear present in v12.43.2 and it may be related to this commit but I'm not 100% yet.
https://github.com/balena-io/balena-cli/commit/ac96616e4e5f9e246dcdfbf38252812f4b3109bb#diff-0ec9ef2f70887932dc2677464f9d6be236e838d0586a1cbf1693d929f262204bL269
