### ISSUE TITLE
Hang using `balena preload`

### ISSUE THREAD

**Issue by meawoppl** [balena-io/balena-cli#2437]
# Expected Behavior

The `balena preload` command should not hang/produce errors

When I run `balena preload balena-cloud-TeleTom-raspberrypi0-2w-64-2.87.16+rev1-v12.11.0.img --app TeleTom --commit 6c18abcb6dbf525b1f1078ba8a2e3247` to patch an image file with the most recent release, it should not hang/crash.

# Actual Behavior

Running the above command gets stuck:
```
(base) meawoppl@monolith:~/repos/bimage$ balena preload balena-cloud-TeleTom-raspberrypi0-2w-64-2.87.16+rev1-v12.11.0.img --app TeleTom --commit 6c18abcb6dbf525b1f1078ba8a2e3247
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting balena settings
| Checking if the image is an edison zip archive
| Creating preloader container
- Starting preloader container
/ Fetching application g_matthew_goodman/teletom
/ Reading image information

[stuck here for >30 minutes]
```
Adding the debug flag generates the following Python traceback quite quickly, and still hangs:

```
(base) meawoppl@monolith:~/repos/bimage$ DEBUG=1 balena preload balena-cloud-TeleTom-raspberrypi0-2w-64-2.87.16+rev1-v12.11.0.img --app TeleTom --commit 6c18abcb6dbf525b1f1078ba8a2e3247
[debug] original argv0="balena" argv=[/home/meawoppl/bin/balena-cli/balena,/snapshot/versioned-source/bin/balena,preload,balena-cloud-TeleTom-raspberrypi0-2w-64-2.87.16+rev1-v12.11.0.img,--app,TeleTom,--commit,6c18abcb6dbf525b1f1078ba8a2e3247] length=8
[debug] new argv=[/home/meawoppl/bin/balena-cli/balena,/snapshot/versioned-source/bin/balena,preload,balena-cloud-TeleTom-raspberrypi0-2w-64-2.87.16+rev1-v12.11.0.img,--app,TeleTom,--commit,6c18abcb6dbf525b1f1078ba8a2e3247] length=8
Building Docker preloader image. [===                     ] 12%
Step 1/7 : FROM docker:17.12.0-ce-dind
Building Docker preloader image. [======                  ] 25%
Step 2/7 : RUN apk update && apk add --no-cache python3 parted btrfs-progs util-linux sfdisk file coreutils sgdisk
 ---> Using cache
Building Docker preloader image. [=========               ] 37%
Step 3/7 : COPY ./requirements.txt /tmp/
 ---> Using cache
Building Docker preloader image. [============            ] 50%
Step 4/7 : RUN pip3 install -r /tmp/requirements.txt
 ---> Using cache
Building Docker preloader image. [===============         ] 62%
Step 5/7 : COPY ./src /usr/src/app
 ---> Using cache
Building Docker preloader image. [==================      ] 75%
Step 6/7 : WORKDIR /usr/src/app
 ---> Using cache
Building Docker preloader image. [=====================   ] 87%
Step 7/7 : CMD ["python3", "/usr/src/app/preload.py"]
 ---> Using cache
 ---> c38656bce1f6
Successfully built c38656bce1f6
Building Docker preloader image. [========================] 100%
| Checking that the image is a writable file
| Finding a free tcp port and getting balena settings
| Checking if the image is an edison zip archive
| Creating preloader container
/ Starting preloader container
/ Fetching application g_matthew_goodman/teletom
/ Reading image informationTraceback (most recent call last):
  File "/usr/src/app/preload.py", line 954, in <module>
    result = method(**data.get("parameters", {}))
  File "/usr/src/app/preload.py", line 910, in get_image_info
    get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 776, in get_images_and_supervisor_version
    return _get_images_and_supervisor_version()
  File "/usr/src/app/preload.py", line 732, in _get_images_and_supervisor_version
    rootA_file_contents.get("docker_service", ""),
  File "/usr/src/app/preload.py", line 875, in get_docker_storage_driver
    position = find_one_of(words, "-s", "--storage-driver")
  File "/usr/src/app/preload.py", line 865, in find_one_of
    index = lst.index(elem)
ValueError: '-s' is not in list
| Reading image information
```

# Steps to Reproduce the Problem

See above?

# Specifications

- **balena CLI version:** e.g. 1.2.3 `(base) balena-cli version "12.44.6" Node.js version "12.18.1"`

- **Cloud backend:** balenaCloud
- **Operating system version:** 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
- **32/64 bit OS and processor:** 64bit  64-bit Intel processor
- **Install method:** zip package

**Comment by meawoppl** [comment]
Updating to balena-cli version `13.1.6` seems to fix this. This requires the change of the `--app` flag to `--fleet`, but otherwise ran without a hitch.
