### ISSUE TITLE
ECONNRESET: socket hang up - scanning for device

### ISSUE THREAD

**Issue by 20k-ultra** [balena-io/balena-cli#2448]
# Expected Behavior

expected `balena scan` to return list of devices on my network

# Actual Behavior

pretty consistently get `ECONNRESET: socket hang up` error but I have really rare occasions I do not! 

```
mig@ghost ~$ sudo balena --debug scan
[debug] new argv=[/home/mig/.local/balena-cli/balena,/snapshot/versioned-source/bin/balena,scan] length=3 
[debug] Deprecation check: 0.09649 days since last npm registry query for next major version release date. 
[debug] Will not query the registry again until at least 7 days have passed. 
Scanning for local balenaOS devices... ! 
ECONNRESET: socket hang up 
Error: socket hang up 
    at connResetException (internal/errors.js:609:14) 
    at Socket.socketCloseListener (_http_client.js:400:25) 
    at Socket.emit (events.js:327:22) 
    at Socket.EventEmitter.emit (domain.js:482:12) 
    at TCP.<anonymous> (net.js:674:12) 
For further help or support, visit: 
https://www.balena.io/docs/reference/balena-cli/#support-faq-and-troubleshooting 

```

**Comment by 20k-ultra** [comment]
After debugging this I found that this error is being thrown because one of my device is giving the CLI issues. Once I disconnected that device from my network the CLI never threw this error again and correctly scanned balenaOS devices on my network.

 - [Raspberry Pi (v1 / Zero / Zero W)] Raspberry Pi (v1 / Zero / Zero W)
- balenaOS 2.83.21+rev1 development
 - Supervisor v12.10.3

**Comment by 20k-ultra** [comment]
Increasing the dockerTimout to 10 seconds solved the issue. So, I think the problem is that the device was slow to respond due to load and the CLI then would timeout the connection.

I'm not sure how to solve this issue permanently though. It's interesting that if you have say 100 devices on your network and 1 of those devices is at 100% cpu load and thus does not respond to the CLI querying the engine then you'll get no info on the other 99 devices. Therefore, the timeout could be per device and maybe increased. Making the CLI log device info as they are popular would provide a good UX since you will get feedback right away but then be able to log the device that's slow and error on that one (preferably handle it nicer then throwing an exception)
